export type OfficeProgram = "WORD" | "POWERPOINT" | "EXCEL";
export type QuestionSeed = {
  program: OfficeProgram;
  questionText: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: "A" | "B" | "C" | "D";
};

export const OFFICE_EXAM_QUESTIONS: QuestionSeed[] = [
  {
    program: "WORD",
    questionText: "En Word 2019, necesitas cambiar una página específica a orientación horizontal dentro de un documento vertical. ¿Qué acción es correcta?",
    optionA: "Insertar un salto de sección antes y después, y cambiar la orientación en esa sección",
    optionB: "Cambiar la orientación desde Diseño y Word lo aplicará solo a la página activa automáticamente",
    optionC: "Usar Ctrl+L para alternar orientación de página",
    optionD: "Aplicar columnas en lugar de orientación",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "¿Qué atajo de teclado guarda el documento activo en Word 2019?",
    optionA: "Ctrl+S",
    optionB: "Ctrl+G",
    optionC: "F12",
    optionD: "Alt+F4",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "Quieres generar una tabla de contenido automática. ¿Qué requisito es indispensable?",
    optionA: "Aplicar estilos de encabezado (Título 1, Título 2, etc.)",
    optionB: "Insertar números de página en todas las hojas",
    optionC: "Activar control de cambios",
    optionD: "Convertir el archivo a PDF primero",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "¿Cuál es la forma más rápida de insertar un salto de página manual en Word?",
    optionA: "Ctrl+Enter",
    optionB: "Ctrl+Shift+Enter",
    optionC: "Alt+Enter",
    optionD: "F5",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "¿Para qué se utiliza un salto de sección \"Página siguiente\"?",
    optionA: "Para comenzar una nueva sección en la página siguiente con formato independiente",
    optionB: "Para insertar una línea horizontal decorativa",
    optionC: "Para dividir una palabra en sílabas",
    optionD: "Para bloquear la edición del documento",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "Debes aumentar el interlineado de varios párrafos seleccionados a 1.5. ¿Dónde lo haces?",
    optionA: "Inicio > Párrafo > Interlineado y espaciado",
    optionB: "Insertar > Formas",
    optionC: "Revisar > Idioma",
    optionD: "Vista > Zoom",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "Necesitas que la numeración de página comience en la tercera hoja. ¿Qué estrategia es correcta?",
    optionA: "Insertar un salto de sección, desvincular encabezado/pie y configurar inicio de numeración",
    optionB: "Cambiar la fuente de la numeración a blanco en las primeras dos páginas",
    optionC: "Usar solo salto de línea en la segunda página",
    optionD: "No es posible en Word 2019",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "Quieres reemplazar todos los dobles espacios por un espacio simple. ¿Qué herramienta usas?",
    optionA: "Buscar y reemplazar (Ctrl+H)",
    optionB: "Control de cambios",
    optionC: "Ortografía y gramática",
    optionD: "Panel de navegación",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "Si modificas el estilo \"Título 2\", ¿qué ocurre en el documento?",
    optionA: "Se actualizan automáticamente todos los textos con ese estilo",
    optionB: "Solo cambia el primer párrafo con ese estilo",
    optionC: "Se eliminan los demás estilos",
    optionD: "El cambio no se guarda",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "¿En qué pestaña se activa \"Control de cambios\" en Word 2019?",
    optionA: "Revisar",
    optionB: "Diseño",
    optionC: "Correspondencia",
    optionD: "Vista",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "Debes aceptar todas las ediciones propuestas en un documento. ¿Qué comando usas?",
    optionA: "Revisar > Aceptar > Aceptar todos los cambios",
    optionB: "Inicio > Borrar formato",
    optionC: "Archivo > Guardar como",
    optionD: "Insertar > Comentario",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "¿Qué elemento inserta una referencia numerada al pie de la página?",
    optionA: "Nota al pie",
    optionB: "Marcador",
    optionC: "Hipervínculo",
    optionD: "Título",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "En una combinación de correspondencia, ¿qué archivo suele usarse como origen de datos de destinatarios?",
    optionA: "Una hoja de Excel con columnas como Nombre, Apellido y Correo",
    optionB: "Una presentación de PowerPoint",
    optionC: "Un PDF protegido",
    optionD: "Un archivo de imagen PNG",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "Necesitas generar etiquetas postales para una lista de clientes. ¿Qué funcionalidad de Word corresponde?",
    optionA: "Correspondencia > Iniciar combinación de correspondencia > Etiquetas",
    optionB: "Diseño > Marca de agua",
    optionC: "Vista > Ventana nueva",
    optionD: "Revisar > Traducir",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "Tienes texto separado por tabulaciones y quieres convertirlo en tabla. ¿Qué opción es correcta?",
    optionA: "Insertar > Tabla > Convertir texto en tabla",
    optionB: "Inicio > Copiar formato",
    optionC: "Revisar > Comparar",
    optionD: "Archivo > Exportar",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "Quieres evitar que un encabezado quede al final de la página separado de su párrafo. ¿Qué ajuste aplicas?",
    optionA: "Párrafo > Líneas y saltos de página > Conservar con el siguiente",
    optionB: "Insertar > Salto de página manual antes de cada título",
    optionC: "Disminuir el zoom",
    optionD: "Usar solo texto en negrita",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "¿Qué herramienta permite insertar una referencia cruzada a una tabla o figura ya numerada?",
    optionA: "Referencias > Referencia cruzada",
    optionB: "Insertar > Ecuación",
    optionC: "Revisar > Comentario nuevo",
    optionD: "Diseño > Temas",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "Debes permitir solo el llenado de formularios en un documento. ¿Qué opción utilizas?",
    optionA: "Revisar > Restringir edición",
    optionB: "Archivo > Compartir",
    optionC: "Inicio > Seleccionar > Seleccionar todo",
    optionD: "Insertar > Objeto",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "¿Qué atajo elimina el formato de carácter directo (negrita, color, etc.) en el texto seleccionado?",
    optionA: "Ctrl+Barra espaciadora",
    optionB: "Ctrl+Shift+C",
    optionC: "Ctrl+M",
    optionD: "Alt+Shift+5",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "¿Qué tecla repite la última acción realizada en Word 2019?",
    optionA: "F4",
    optionB: "F7",
    optionC: "F12",
    optionD: "Esc",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "Necesitas que varias columnas de una tabla tengan el mismo ancho rápidamente. ¿Qué comando usas?",
    optionA: "Herramientas de tabla > Presentación > Distribuir columnas",
    optionB: "Diseño > Color de página",
    optionC: "Inicio > Justificar",
    optionD: "Insertar > WordArt",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "¿Dónde se inserta una marca de agua de tipo \"Borrador\" en Word 2019?",
    optionA: "Diseño > Marca de agua",
    optionB: "Revisar > Proteger",
    optionC: "Vista > Esquema",
    optionD: "Insertar > Encabezado",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "Para mejorar accesibilidad, quieres describir una imagen para lectores de pantalla. ¿Qué debes editar?",
    optionA: "Texto alternativo de la imagen",
    optionB: "Nombre del archivo DOCX",
    optionC: "Pie de página del documento",
    optionD: "Idioma de corrección",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "¿Qué panel facilita navegar por títulos y reordenar secciones largas de un informe?",
    optionA: "Panel de navegación",
    optionB: "Portapapeles",
    optionC: "Panel de animación",
    optionD: "Inspector de documento",
    correctOption: "A",
  },
  {
    program: "WORD",
    questionText: "Debes agregar citas bibliográficas con formato APA en un trabajo. ¿Qué pestaña concentra estas herramientas?",
    optionA: "Referencias",
    optionB: "Correspondencia",
    optionC: "Vista",
    optionD: "Ayuda",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "¿Qué atajo inserta una nueva diapositiva en PowerPoint 2019?",
    optionA: "Ctrl+M",
    optionB: "Ctrl+N",
    optionC: "Ctrl+Shift+M",
    optionD: "F6",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "Quieres cambiar la estructura de una diapositiva (título y contenido, dos contenidos, etc.) sin alterar el tema. ¿Qué usas?",
    optionA: "Inicio > Diseño de diapositiva",
    optionB: "Transiciones > Opciones de efecto",
    optionC: "Insertar > Cuadro de texto",
    optionD: "Archivo > Información",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "Necesitas mostrar fecha y número de diapositiva en toda la presentación. ¿Qué ruta es correcta?",
    optionA: "Insertar > Encabezado y pie de página > Aplicar a todo",
    optionB: "Revisar > Ortografía",
    optionC: "Vista > Patrón de documentos",
    optionD: "Diseño > Variantes",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "¿Qué atajo duplica rápidamente un objeto seleccionado en una diapositiva?",
    optionA: "Ctrl+D",
    optionB: "Ctrl+R",
    optionC: "Shift+D",
    optionD: "Alt+D",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "Durante edición, quieres iniciar la presentación desde la diapositiva actual. ¿Qué combinación usas?",
    optionA: "Shift+F5",
    optionB: "F5",
    optionC: "Ctrl+F5",
    optionD: "Alt+F5",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "Para ver tus notas en el monitor del presentador y la diapositiva en proyector, ¿qué modo debes activar?",
    optionA: "Vista del moderador",
    optionB: "Vista de esquema",
    optionC: "Vista de lectura",
    optionD: "Vista clasificador de diapositivas",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "¿Qué transición de PowerPoint 2019 permite animar el movimiento suave de objetos entre dos diapositivas relacionadas?",
    optionA: "Transformación (Morph)",
    optionB: "Cortar",
    optionC: "Empujar",
    optionD: "Barrido",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "Quieres que los viñetas aparezcan una por una dentro del mismo cuadro de texto. ¿Dónde lo configuras?",
    optionA: "Animaciones > Opciones de efecto > Por párrafo",
    optionB: "Insertar > Formas",
    optionC: "Diseño > Tamaño de diapositiva",
    optionD: "Archivo > Imprimir",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "Necesitas que una animación inicie al hacer clic en una forma específica, no al clic general de la diapositiva. ¿Qué usas?",
    optionA: "Animaciones > Desencadenador",
    optionB: "Transiciones > Avanzar diapositiva",
    optionC: "Revisar > Comentario nuevo",
    optionD: "Vista > Zoom",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "Para alinear varios objetos seleccionados al centro vertical, ¿qué comando aplica?",
    optionA: "Formato de forma > Alinear > Alinear al medio",
    optionB: "Inicio > Organizar > Traer al frente",
    optionC: "Insertar > Iconos",
    optionD: "Diseño > Formato de fondo",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "Tienes tres iconos y deseas distribuirlos con separación uniforme horizontal. ¿Qué opción eliges?",
    optionA: "Alinear > Distribuir horizontalmente",
    optionB: "Alinear > Ajustar a la cuadrícula",
    optionC: "Ordenar > Enviar atrás",
    optionD: "Vista > Escala de grises",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "¿Qué función combina o recorta formas para crear diseños personalizados en una sola silueta?",
    optionA: "Combinar formas",
    optionB: "Formato rápido",
    optionC: "Insertar SmartArt",
    optionD: "Comprimir imágenes",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "Tu presentación incluye videos pesados y el archivo creció demasiado. ¿Qué acción ayuda a reducir tamaño?",
    optionA: "Archivo > Información > Comprimir medios",
    optionB: "Inicio > Restablecer diapositiva",
    optionC: "Revisar > Idioma",
    optionD: "Vista > Patrón de notas",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "Quieres evitar que cambie la tipografía al abrir en otro equipo sin esas fuentes. ¿Qué debes hacer al guardar?",
    optionA: "Incrustar fuentes en el archivo",
    optionB: "Guardar solo en formato PDF",
    optionC: "Usar siempre vista protegida",
    optionD: "Desactivar revisión ortográfica",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "¿Para qué sirven las secciones en PowerPoint?",
    optionA: "Para organizar grupos de diapositivas por bloques temáticos",
    optionB: "Para aplicar una transición distinta a cada objeto",
    optionC: "Para proteger con contraseña solo una diapositiva",
    optionD: "Para convertir diapositivas en tablas",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "Necesitas insertar diapositivas de otra presentación conservando, si quieres, su formato original. ¿Qué herramienta usas?",
    optionA: "Reutilizar diapositivas",
    optionB: "Duplicar diapositiva",
    optionC: "Inspector de documento",
    optionD: "Insertar comentario",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "Deseas generar un documento de apoyo en Word con miniaturas y notas de presentación. ¿Qué opción corresponde?",
    optionA: "Exportar > Crear documentos (Handouts) en Word",
    optionB: "Guardar como plantilla POTX",
    optionC: "Insertar > Objeto",
    optionD: "Archivo > Cerrar",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "¿Dónde cambias una presentación de formato estándar 4:3 a panorámico 16:9?",
    optionA: "Diseño > Tamaño de diapositiva",
    optionB: "Transiciones > Duración",
    optionC: "Animaciones > Panel de animación",
    optionD: "Revisar > Comparar",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "Quieres que una diapositiva exista en el archivo pero no se muestre durante la exposición normal. ¿Qué haces?",
    optionA: "Marcarla como Ocultar diapositiva",
    optionB: "Moverla al patrón de diapositivas",
    optionC: "Bloquearla con contraseña",
    optionD: "Aplicar transición Ninguna",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "Para que la presentación se repita automáticamente en un kiosco hasta presionar Esc, ¿qué configuración usas?",
    optionA: "Configurar presentación > Repetir el ciclo continuamente hasta Esc",
    optionB: "Ensayar intervalos",
    optionC: "Ocultar todas las diapositivas",
    optionD: "Cambiar a vista de lectura",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "Una imagen tiene fondo no deseado y quieres eliminarlo sin salir de PowerPoint. ¿Qué comando aplica?",
    optionA: "Formato de imagen > Quitar fondo",
    optionB: "Insertar > Captura",
    optionC: "Diseño > Ideas de diseño",
    optionD: "Transiciones > Desvanecer",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "Necesitas aplicar el mismo formato a varios objetos no contiguos rápidamente. ¿Qué técnica es correcta?",
    optionA: "Doble clic en Copiar formato para mantenerlo activo",
    optionB: "Usar Ctrl+P en cada objeto",
    optionC: "Aplicar transición a todos",
    optionD: "Cambiar el tamaño de diapositiva",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "¿Qué atajo agrupa varios objetos seleccionados en PowerPoint 2019?",
    optionA: "Ctrl+G",
    optionB: "Ctrl+Shift+G",
    optionC: "Alt+G",
    optionD: "F4",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "Para ajustar el orden y tiempo de varias animaciones en una diapositiva, ¿qué panel debes abrir?",
    optionA: "Panel de animación",
    optionB: "Panel de selección",
    optionC: "Panel de portapapeles",
    optionD: "Panel de notas",
    correctOption: "A",
  },
  {
    program: "POWERPOINT",
    questionText: "Quieres entregar la presentación como video MP4. ¿Qué ruta usas?",
    optionA: "Archivo > Exportar > Crear un video",
    optionB: "Inicio > Nueva diapositiva",
    optionC: "Revisar > Diccionario",
    optionD: "Insertar > WordArt",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "¿Qué atajo convierte un rango de datos en una tabla estructurada en Excel 2019?",
    optionA: "Ctrl+T",
    optionB: "Ctrl+L",
    optionC: "Ctrl+Shift+T",
    optionD: "Alt+T",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Copias una fórmula y quieres fijar siempre la columna y la fila de una celda de referencia. ¿Qué tipo de referencia usas?",
    optionA: "Referencia absoluta con signos $ (por ejemplo, $B$2)",
    optionB: "Referencia relativa (por ejemplo, B2)",
    optionC: "Referencia externa sin libro",
    optionD: "Nombre de hoja sin celda",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Necesitas sumar ventas cuando Región=\"Norte\" y Producto=\"Laptop\". ¿Qué función es la más adecuada?",
    optionA: "SUMAR.SI.CONJUNTO",
    optionB: "SUMAR.SI",
    optionC: "CONTAR.SI",
    optionD: "MAX",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "¿Qué función cuenta celdas no vacías en un rango?",
    optionA: "CONTARA",
    optionB: "CONTAR",
    optionC: "CONTAR.BLANCO",
    optionD: "SUMA",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Debes buscar el precio de un código ubicado en la primera columna de una tabla y devolver valor de otra columna con coincidencia exacta. ¿Qué fórmula es correcta?",
    optionA: "BUSCARV(codigo, tabla, columna, FALSO)",
    optionB: "BUSCARV(codigo, tabla, columna, VERDADERO)",
    optionC: "SUMAR.SI(codigo, tabla)",
    optionD: "SI.ERROR(codigo)",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Necesitas traer un valor desde una columna a la izquierda de la clave de búsqueda. ¿Qué opción es más flexible?",
    optionA: "Combinar INDICE y COINCIDIR",
    optionB: "BUSCARV con coincidencia aproximada",
    optionC: "PROMEDIO",
    optionD: "DESREF sin argumentos",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Tienes una lista de clientes y quieres eliminar registros repetidos por correo electrónico. ¿Qué herramienta usas?",
    optionA: "Datos > Quitar duplicados",
    optionB: "Inicio > Dar formato como tabla",
    optionC: "Fórmulas > Administrador de nombres",
    optionD: "Vista > Inmovilizar paneles",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Quieres limitar una celda para que solo acepte valores de una lista desplegable. ¿Dónde se configura?",
    optionA: "Datos > Validación de datos > Lista",
    optionB: "Revisar > Proteger libro",
    optionC: "Insertar > Segmentación de datos",
    optionD: "Inicio > Buscar y seleccionar",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Para resaltar rápidamente valores duplicados en una columna, ¿qué usas?",
    optionA: "Formato condicional > Reglas para resaltar celdas > Valores duplicados",
    optionB: "Ordenar de A a Z",
    optionC: "Quitar duplicados",
    optionD: "Pegado especial",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Importaste datos en una sola columna separados por punto y coma. ¿Qué herramienta los divide en columnas?",
    optionA: "Datos > Texto en columnas",
    optionB: "Inicio > Ajustar texto",
    optionC: "Fórmulas > Autosuma",
    optionD: "Insertar > Tabla dinámica",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "¿Qué comando mantiene visible la primera fila mientras te desplazas hacia abajo?",
    optionA: "Vista > Inmovilizar paneles > Inmovilizar fila superior",
    optionB: "Vista > Nueva ventana",
    optionC: "Datos > Filtro",
    optionD: "Inicio > Formato",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Necesitas resumir miles de filas por región y mes con posibilidad de arrastrar campos. ¿Qué herramienta es ideal?",
    optionA: "Tabla dinámica",
    optionB: "Formato condicional",
    optionC: "Escenarios",
    optionD: "Consolidar",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Dentro de una tabla dinámica, ¿cómo muestras ventas como porcentaje del total general?",
    optionA: "Configuración de campo de valor > Mostrar valores como > % del total general",
    optionB: "Cambiar formato de número a porcentaje y nada más",
    optionC: "Aplicar una regla de color",
    optionD: "Usar BUSCARV en cada celda",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Tienes una columna con nombres y otra con apellidos, y en una tercera escribes el nombre completo de ejemplo. ¿Qué función puede completar el patrón automáticamente?",
    optionA: "Relleno rápido (Ctrl+E)",
    optionB: "Ordenar personalizado",
    optionC: "Buscar objetivo",
    optionD: "Consolidar",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Al editar una fórmula, quieres alternar rápidamente entre referencia relativa, absoluta y mixta de una celda seleccionada. ¿Qué tecla usas?",
    optionA: "F4",
    optionB: "F2",
    optionC: "F7",
    optionD: "F9",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Debes obtener subtotales por categoría en una lista. ¿Qué procedimiento es correcto antes de aplicar Subtotales?",
    optionA: "Ordenar previamente los datos por la columna de categoría",
    optionB: "Crear una tabla dinámica obligatoriamente",
    optionC: "Bloquear la hoja",
    optionD: "Combinar todas las celdas del rango",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Si conoces el resultado deseado de una fórmula y necesitas hallar el valor de entrada que lo produce, ¿qué herramienta usas?",
    optionA: "Buscar objetivo",
    optionB: "Quitar duplicados",
    optionC: "Validación de datos",
    optionD: "Administrador de nombres",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Quieres proteger una hoja para que solo se editen celdas desbloqueadas. ¿Qué opción corresponde?",
    optionA: "Revisar > Proteger hoja",
    optionB: "Datos > Agrupar",
    optionC: "Archivo > Compartir",
    optionD: "Vista > Dividir",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "¿Qué tecla permite editar directamente el contenido de la celda activa sin usar la barra de fórmulas?",
    optionA: "F2",
    optionB: "F1",
    optionC: "F6",
    optionD: "Esc",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "¿Qué atajo inserta la fecha actual (estática) en una celda?",
    optionA: "Ctrl+;",
    optionB: "Ctrl+:",
    optionC: "Ctrl+Shift+;",
    optionD: "Alt+;",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Necesitas unir Nombre y Apellido con un espacio entre ambos. ¿Qué fórmula es válida?",
    optionA: "=A2&\" \"&B2",
    optionB: "=SUMA(A2,B2)",
    optionC: "=UNIRCADENAS(A2,B2)",
    optionD: "=ESPACIOS(A2,B2)",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Quieres calcular el promedio de ventas solo para una región y un año específicos. ¿Qué función aplica mejor?",
    optionA: "PROMEDIO.SI.CONJUNTO",
    optionB: "PROMEDIO",
    optionC: "SUMAR.SI.CONJUNTO",
    optionD: "MEDIANA",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Tienes dos series en un gráfico con escalas muy diferentes. ¿Qué mejora permite compararlas mejor sin distorsión?",
    optionA: "Asignar una de las series al eje secundario",
    optionB: "Cambiar todo a gráfico circular",
    optionC: "Eliminar una serie",
    optionD: "Aplicar color rojo a ambas",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Para usar una referencia legible en fórmulas como =SUMA(Ventas_Q1), ¿qué debes crear primero?",
    optionA: "Un nombre de rango",
    optionB: "Un comentario en la celda",
    optionC: "Una regla de validación",
    optionD: "Una macro obligatoria",
    correctOption: "A",
  },
  {
    program: "EXCEL",
    questionText: "Necesitas identificar de qué celdas depende una fórmula compleja. ¿Qué herramienta de auditoría usas?",
    optionA: "Rastrear precedentes",
    optionB: "Rastrear dependientes",
    optionC: "Evaluar fórmula de manera manual en papel",
    optionD: "Comprobación de errores del sistema operativo",
    correctOption: "A",
  },
];
