import { assignParagraphs } from "./lecturaGenerate.js";

export type WidgetTema = {
  id: string;
  nombre: string;
  titulo: string;
  mision: string;
  clave: string[];
  preguntaGuia: string;
  organizador: Array<{ caja: string; hijos: string }>;
  parrafos: string[];
};

/** Un widget por equipo (columna de color). El orden sigue las butacas A→F. */
export const TKINTER_WIDGET_TEMAS: WidgetTema[] = [
  {
    id: "frame",
    nombre: "Frame",
    titulo: "Frame: la ventana se organiza en cajas",
    mision: "Explicar qué es un Frame, para qué existe y por qué no se mezclan los acomodos en el mismo padre.",
    clave: ["Frame", "contenedor", "pack / grid", "zonas de la ventana"],
    preguntaGuia: "Si el Frame no calcula ni guarda datos, ¿para qué sirve entonces en un programa real?",
    organizador: [
      { caja: "Ventana Tk", hijos: "Varios Frame (encabezado, formulario, botones)" },
      { caja: "Cada Frame", hijos: "Un solo idioma de acomodo: pack o grid" },
      { caja: "Error típico", hijos: "Mezclar pack y grid en el mismo padre" },
    ],
    parrafos: [
      "Cuando abres un programa con interfaz gráfica no estás viendo un montón de botones sueltos pegados al azar: estás viendo un sistema de cajas. En Tkinter la ventana principal —Tk o Toplevel— es el contenedor mayor. Dentro de ella puedes colocar etiquetas, entradas y botones, pero si los tiras todos sobre la ventana el diseño se vuelve frágil: un cambio mueve todo y mezclar formas de acomodo provoca errores difíciles de ver. El Frame es un widget cuya misión no es “hacer la tarea del usuario”, sino contener a otros widgets. Piensa en una caja de cartón o en las zonas de un salón: el encabezado, el formulario y los botones de acción. Cada zona tiene su propio orden interno. Leer código de interfaces es, en el fondo, leer arquitectura: quién contiene a quién. Si no ves las cajas, no entiendes la ventana, aunque el programa “sí corra”. Este párrafo pide que el equipo pueda decir en una oración qué es un Frame y para qué existe. Esa oración será el centro del mapa en Canva. Si nadie puede repetirla sin mirar la pantalla, hay que volver a leer. Fomentar la lectura aquí significa resistir la prisa de “ya entendí” y exigir evidencia de comprensión.",
      "Toda zona de una ventana nace de un problema del usuario. Con el Frame hay que preguntarse qué necesidad cubre y qué pasaría si esa caja no existiera. Un programa no se diseña porque “así lo trae el tutorial”: se diseña porque alguien tiene que leer un título, llenar datos o confirmar una acción en un lugar claro. Si quitas un Frame y la interfaz sigue igual de clara, entonces no era esencial; si al quitarlo el usuario se pierde, entonces sí organiza la experiencia. Imaginen a un compañero que nunca ha visto Tkinter: ¿podría explicar, solo con lo que oye ahora, qué dolor evita una caja? No basta con decir “sirve para la interfaz”. Hay que decir a quién le sirve, en qué momento y con qué consecuencia si falta. Esas tres flechas —quién, cuándo, si falta— ya son material del organizador gráfico. Un ejemplo escolar ayuda: pasar lista, elegir turno, entregar un archivo, armar un mini examen. Señalen dónde iría un Frame de encabezado y dónde uno de acciones. El análisis se nota cuando el ejemplo no cabe en otra columna. Lean despacio: el objetivo no es terminar el párrafo, es poder defenderlo frente al grupo.",
      "Tkinter no adivina dónde quieres cada control. Tú se lo dices con un gestor de geometría. pack() apila widgets como bloques: arriba, abajo, izquierda, derecha. grid() piensa en filas y columnas, ideal para formularios. place() usa coordenadas exactas; es preciso, pero rígido si la ventana cambia de tamaño. La regla de oro cabe en una frase: no mezcles pack y grid dentro del mismo contenedor. La ventana puede usar pack para colocar tres Frames, y cada Frame puede usar grid por dentro. Eso no es mezclar: cada caja habla un solo idioma. Si un alumno dice que “no le aparece el botón”, muchas veces el widget sí existe, pero nadie lo acomodó, o dos gestores pelearon por el mismo padre. Leer una interfaz es leer estas decisiones: qué caja, qué idioma, qué hijo. En el mapa deben aparecer dos cajas: “sí se puede” (pack en la ventana y grid dentro de un Frame) y “no se puede” (pack y grid en el mismo padre). Si el organizador no las separa, este párrafo no se comprendió. Vuelvan al texto y extraigan un ejemplo de cada lado, con palabras del salón, no de un tutorial copiado.",
      "Un error de lectura típico es crear controles sin padre claro, o crearlos y olvidar mostrarlos. El widget existe, pero nadie lo sentó. “No se ve” no es un misterio: o no tiene Frame, o no tiene geometría, o está detrás de otra cosa. El análisis consiste en no aceptar “no jala” como diagnóstico. Imaginen que un compañero dice que su botón no aparece. ¿Qué tres preguntas harían antes de tocar una línea? Esas preguntas son comprensión convertida en método. Llévenlas al organizador como un protocolo: si no se ve, preguntar dónde vive, con qué se acomodó y quién es el padre. Relaciónenlo con una caja del salón: un objeto que existe pero no está en su zona no puede usarse. La analogía no reemplaza al concepto; lo hace explicable. Si no pueden contar este error sin jerga, vuelvan a leer. Está escrito para poder enseñarlo. En Canva, una rama de “errores de Frame” enseña más que un icono decorativo. Causa, síntoma y arreglo. Sin las tres, el mapa es un letrero.",
      "El Frame también se relaciona con LabelFrame, que es una caja con título visible: “Datos del alumno”, “Elige un turno”, “Acciones”. El usuario no lee tu intención: lee la pantalla. Si las opciones de un examen y los botones de guardar están mezclados, el grupo se rompe visualmente aunque el código interno sea correcto. Un programador que lee su propio diseño pregunta: ¿se entiende la zona?, ¿se ve el título?, ¿cada Frame tiene una sola función? Diseñar es decir que no: si una caja no tiene función, sobra. Si una función no tiene caja, el plan está incompleto. Recorten. Un caso mínimo basta: encabezado, pregunta, acciones. No necesitan veinte Frames para demostrar el tema. Necesitan que cada pieza tenga un porqué. Cuando el equipo dibuje el mapa, debe poder señalar ventana, Frames y el idioma de cada uno. Si el mapa se puede explicar en un minuto, el código después casi se escribe solo. Leer para programar es ver el sistema antes de teclearlo. Anoten desde ahora el título de su lámina: si solo dice “Frame”, es débil; si nombra las zonas, ya hay análisis.",
      "Cierren con un producto de todo el equipo: un organizador gráfico o mapa cognitivo en Canva. El Frame debe quedar en el centro, las zonas alrededor, la regla de un idioma por padre como flecha, y un error típico como caja de advertencia. Cada integrante leyó un párrafo largo en voz alta; el mapa nace de esos párrafos, no de un resumen de internet. Cualquier compañero de este color debe poder tomar la lámina y continuar. Si solo “el que dibuja” sabe qué hay en Canva, el equipo no leyó junto. Antes de proyectar, ensayen un minuto. Si no les alcanza, hay demasiado texto o demasiado poco orden. Recorten. El objetivo de la sesión es fomentar lectura, análisis y comprensión. El Frame se entiende no cuando se oyó la palabra, sino cuando se pudo organizar. Organicen. Luego expliquen. Nadie lee el texto de otro color. Nadie copia el mapa del equipo de al lado: ustedes leyeron Frame; ellos leyeron otro widget. Esa diferencia es a propósito.",
    ],
  },
  {
    id: "label",
    nombre: "Label",
    titulo: "Label: el texto que el usuario sí lee",
    mision: "Explicar qué comunica un Label, cuándo se actualiza y qué pasa si el mensaje miente.",
    clave: ["Label", "text", "textvariable", "mensaje al usuario"],
    preguntaGuia: "¿Qué debería decir un Label antes de que el usuario actúe, y qué debería decir después?",
    organizador: [
      { caja: "Label fijo", hijos: "Títulos, instrucciones, nombres de campo" },
      { caja: "Label vivo", hijos: "textvariable / config(text=) cuando cambia el estado" },
      { caja: "Error", hijos: "Un mensaje que no depende de lo que el usuario eligió" },
    ],
    parrafos: [
      "Un Label parece lo más simple de Tkinter: una etiqueta de texto. Precisamente por eso se lee mal. Muchos equipos lo tratan como adorno y luego el usuario no sabe qué se le pide. El Label es el primer acto de lectura de la interfaz: nombra, instruye, confirma o avisa. Si el texto es vago —“Dato”, “Cosa”, “Aceptar info”— el usuario adivina. Si el texto es preciso —“Número de control”, “Elige un turno”, “Correcto: era Radiobutton”— el programa enseña. Leer un Label es leer la intención del diseñador. Este párrafo pide que el equipo se detenga y se pregunte qué fenómeno del mundo real está nombrando esa etiqueta. Un Label no calcula; comunica. Quien no puede decir en una oración para qué existe todavía no lo domina, aunque haya copiado diez ejemplos con text=\"Hola\". Fomentar la lectura aquí significa mirar la pantalla como un texto: ¿se entiende la pregunta?, ¿se entiende el resultado?, ¿hay un título que sitúe al usuario? Anoten tres Labels de un trámite escolar y defiendan por qué cada uno es esencial. Esa lista será el centro del mapa en Canva.",
      "Hay Labels fijos y Labels vivos. El fijo no cambia: el nombre de la materia, la instrucción de un formulario, el título de una zona. El vivo sí cambia: “Correcto”, “Falta elegir una opción”, el nombre del alumno después de leer un Entry, el puntaje, la hora. En Tkinter el vivo se logra con textvariable —casi siempre un StringVar— o con config(text=...) cuando ocurre un evento. Sin esa conexión, el clic no deja huella visible: la pantalla se mueve y el mensaje sigue igual. Muchos estudiantes creen que “ya está” cuando ven la etiqueta inicial. La lectura atenta pregunta qué se comparte entre el control que decide y el Label que responde. El valor, el canal y el mensaje son tres ideas distintas. Si las juntan en una sola palabra, el mapa miente. Practiquen en voz alta: el usuario elige o escribe, algo se guarda, el Label lee y muestra. Si no pueden llenar esas estaciones, vuelvan a este párrafo. El organizador debe tener una caja de “Label fijo” y otra de “Label que responde”. Sin las dos, comprendieron a medias.",
      "Un Label que no depende de la elección es teatro. Un mensaje que siempre dice “OK” aunque el usuario no haya hecho nada enseña una regla falsa. Leer el diseño incluye leer el estado al arrancar y el estado después de la acción. Un programa que nace en silencio obliga a adivinar; un programa que miente con un texto bonito es peor. Pregunten qué debería decir el Label si el usuario no elige, si elige bien y si elige mal. Tres textos, tres situaciones. Eso es análisis, no adorno. Relaciónenlo con un recado del plantel: un aviso que no cambia aunque cambie la fecha no sirve. El Label vivo es el recado que se actualiza. En Canva dibujen el viaje del dato hasta el texto. Un mapa sin ese viaje es un dibujo de la pantalla, no del sistema. Incluyan lo invisible: la variable. El usuario no la ve, pero si falta, el Label no puede decir la verdad. Señalen lo invisible a propósito en la exposición. Esa frase —“esto no se ve, pero si falta se rompe el mensaje”— demuestra comprensión.",
      "El Label también se relaciona con el Frame: una zona sin título es una caja muda. LabelFrame existe precisamente para ponerle nombre a un grupo. “Elige un lenguaje”, “Datos del alumno”, “Resultado”. El usuario lee esos títulos antes de leer el código, porque el usuario no va a leer el código. Un programador que lee su propia interfaz pregunta si un extraño entendería la ventana en cinco segundos. Si no, el problema suele ser de Labels, no de “más botones”. Este párrafo pide borrar. Si un Label no tiene función, sobra. Si una función no tiene Label, el plan está incompleto. Recorten textos largos: el Label no es un ensayo, es una idea principal. En comprensión lectora, recortar es señalar lo esencial. Hagan el ejercicio: un integrante propone un Label de más, otro defiende por qué sobra, un tercero decide. Esa conversación es el producto intelectual. Canva solo la va a fotografiar. No copien etiquetas de un tutorial en inglés si el usuario de esta clase lee en español. Nombrar en el idioma del usuario también es leer el problema.",
      "Errores típicos: olvidar pack, grid o place y el Label “no aparece”; poner un text que no coincide con lo que el programa hace; actualizar el Label en el lugar equivocado, antes de leer la variable; usar un IntVar donde iba un StringVar y el mensaje sale raro. Cada error tiene un síntoma en pantalla y una causa en el código. La lectura experta mueve la mirada de un lado al otro. Construyan una tabla “se ve / no se ve”. En Canva pueden ser dos columnas. Inventen un ejemplo escolar: un Label que dice “Guardado” aunque nadie guardó. ¿Qué falló: el texto, el evento o la lectura del valor? Esa pregunta debe poder responderse después de oír todos los párrafos de este equipo. No mezclen este tema con Radiobutton o Entry: ustedes leen Label. Los otros equipos tienen su widget. Si el mapa podría colgarse en otra columna sin que nadie note el cambio, no hubo apropiación del texto. Usen un detalle del salón —lista, recado, permiso— que amarre el Label con una comunicación real.",
      "El producto es un solo organizador de todo el equipo. El Label queda al centro; a un lado los fijos, al otro los vivos; abajo el viaje del dato; una caja de error de mensaje que miente. Cada integrante lee en voz alta su párrafo largo. Luego el equipo plasma esas ideas en Canva y expone. Cualquier integrante explica. El criterio de éxito no es que la lámina se vea llena: es que un compañero de otro color pueda repetir cuándo un Label debe cambiar y qué pasa si no cambia. Si no puede, no hubo enseñanza. Antes de proyectar, reciten sin mirar el párrafo: qué es, para qué, fijo o vivo, un error. Quien se trabe vuelve a su texto. Así se fomenta la lectura: con una exigencia clara de lo que hay que entender, no con un resumen de dos líneas. Canva no piensa por ustedes; ustedes piensan y Canva lo muestra. Este equipo leyó Label. Defiendan ese recorte.",
    ],
  },
  {
    id: "radiobutton",
    nombre: "Radiobutton",
    titulo: "Radiobutton: una, y solo una",
    mision: "Definir qué problema resuelve un grupo de radios y cómo se unen con una variable compartida.",
    clave: ["Radiobutton", "variable compartida", "value", "exclusión mutua"],
    preguntaGuia: "¿En qué se parece un grupo de radios a una pregunta de examen de opción única?",
    organizador: [
      { caja: "Pregunta de una sola respuesta", hijos: "Grupo de Radiobutton" },
      { caja: "Canal", hijos: "Una StringVar o IntVar para todos" },
      { caja: "Cada radio", hijos: "text + value distinto + la misma variable" },
    ],
    parrafos: [
      "Hay preguntas que no admiten “un poco de todo”: turno matutino o vespertino; guardar en .txt o en .csv; dificultad fácil, media o difícil. El Radiobutton —botón de opción— existe para ese tipo de decisión. Visualmente parece un círculo que se rellena al elegirlo. Lo importante no es el círculo, sino el grupo: varios radios que comparten la misma variable de control. Cuando marcas uno, los demás del grupo se apagan solos. Si cada radio tuviera su propia variable, dejarían de ser un grupo y podrías “elegir” varios a la vez, que es exactamente lo que no quieres. Un Checkbutton, en cambio, sí permite combinaciones. Leer bien el enunciado de un programa es decidir el widget: ¿es exclusión mutua o acumulación? Esa lectura previa ahorra rediseños enteros. Este párrafo pide una oración: qué problema resuelve el Radiobutton. Anótenla. Será el centro del mapa. Si la oración podría servir igual para un Checkbutton, todavía no distinguieron. Distinguir no es ser quisquilloso; es comprender.",
      "Un Radiobutton solo se entiende con sus compañeros si todos escuchan el mismo canal. Ese canal es una variable de Tkinter: IntVar() si los valores son números, StringVar() si son textos. Cada radio declara value= —por ejemplo 1, 2, 3 o \"python\", \"java\", \"c\"—. Al hacer clic, la variable toma ese value. Con .get() lees la elección; con .set() la cambias por código, útil para un valor inicial. El parámetro command= apunta a una función que se dispara al cambiar la opción: actualizar una etiqueta, habilitar un botón, mostrar un mensaje. Sin variable compartida, los radios son islas. Sin value distinto, no sabes qué eligió el usuario. Sin leer el tipo de variable, mezclas 1 con \"1\" y el programa “no selecciona”. En programación, las palabras invisibles —variable, valor, evento— son tan lectura como el texto en pantalla. Practiquen: canal, valor, respuesta. Tres piezas. En Canva, tres cajas con flechas. Un oyente de otro equipo debería poder repetirlas. Si no puede, el organizador no enseñó: solo decoró.",
      "El estado inicial también se lee. Si la interfaz arranca en blanco sin .set(), el usuario no sabe qué está elegido. Si dos radios tienen el mismo value, el programa no distingue aunque los textos en pantalla sean distintos. Ambos son fallos de comprensión del enunciado: no se leyó qué decisión se estaba modelando. Pregunten qué decisión modela un trámite escolar —turno, materia, formato de entrega—. Si la decisión admite dos verdades a la vez, el control está mal elegido: no es radio. Si admite una sola y aun así se puede marcar doble, el grupo está mal armado: faltó el canal compartido. Este párrafo conecta error con intención. El organizador debe tener “estado inicial” y “valores distintos”. Sin ellas, memorizaron síntomas y no causas. Parafraseen con un examen de opción única. El radio es esa pregunta. El Checkbutton sería “marca todas las que apliquen”. Si no pueden decir esa diferencia en una frase, vuelvan al texto. La diferencia es el análisis más valioso de este bloque.",
      "Agrupen los radios en un Frame o LabelFrame con un título: “Elige un lenguaje”. El usuario no lee tu código: lee la pantalla. Si las opciones de un examen y los botones de guardar están mezclados, el grupo se rompe visualmente aunque la variable sea correcta. Un programador que lee su propio diseño pregunta: ¿se entiende la pregunta?, ¿se ve el grupo?, ¿hay un valor claro al inicio? Esa lectura crítica es parte del oficio. Relaciónenlo con el salón: una pregunta oral donde todos hablan a la vez no es un grupo de radios; una pregunta donde solo una respuesta vale, sí. En el mapa, el LabelFrame no es adorno: es la zona que hace visible la exclusión mutua. Un caso mínimo: tres radios, una StringVar llamada respuesta, un botón que lee respuesta.get(). No necesitan veinte controles. Necesitan que cada pieza tenga un porqué. Si pueden señalar ventana, grupo, variable y acción, ya pueden programarlo después. El caso se vuelve creíble cuando el dato viaja: se elige, se guarda, se pregunta, se muestra.",
      "Errores de lectura que ahorran veinte minutos: crear radios sin variable, o con una variable distinta para cada uno; olvidar pack o grid; meter pack y grid en el mismo Frame; value iguales; no agrupar con título. Un error se ve en la pantalla —dos marcas, ninguna, un hueco—. Otro solo se ve en el código —dos variables que parecen un grupo y no lo son—. La lectura experta mueve la mirada de un lado al otro. Listen tres fallos y una reparación concreta. “Hay que checarlo” no es reparación. “Este grupo necesita un solo canal y values distintos” sí lo es. Amárrenlos al Radiobutton, no a un tema genérico de depuración. Este equipo no entrega una lista de internet. Entrega una lectura analizada. En la exposición, no lean otra vez los párrafos: señalen el mapa y cuenten causa, síntoma y arreglo. Quien no pueda hacerlo vuelve a su párrafo. Así se fomenta la comprensión: con una exigencia pública, no con un dibujo que nadie explica.",
      "El producto es un solo mapa en Canva de todo el equipo. Centro: Radiobutton y exclusión mutua. Ramas: variable compartida, value, estado inicial, LabelFrame, un error, un caso escolar. Cada integrante leyó en voz alta su párrafo largo. El mapa nace de esos párrafos. Cualquier integrante expone. El criterio: un compañero de otro color debe poder decir cuándo usar radio y cuándo no. Si responde “para la interfaz”, no comprendió. Si responde “cuando el usuario debe elegir una sola opción y las demás se apagan”, sí. Antes de proyectar, reciten esa frase. Este equipo leyó Radiobutton; el de al lado leyó otro widget a propósito. No copien su lámina. Lean, analicen, organicen, expliquen.",
    ],
  },
  {
    id: "checkbutton",
    nombre: "Checkbutton",
    titulo: "Checkbutton: varias marcas a la vez",
    mision: "Explicar cuándo sí se pueden combinar opciones y cómo se guarda cada marca.",
    clave: ["Checkbutton", "BooleanVar / IntVar", "combinación", "onvalue / offvalue"],
    preguntaGuia: "¿Qué se rompe si usas un Checkbutton para una decisión que admite una sola respuesta?",
    organizador: [
      { caja: "Varias verdades a la vez", hijos: "Un Checkbutton por opción" },
      { caja: "Cada marca", hijos: "Su propia variable (no un solo canal para todas)" },
      { caja: "No usar si", hijos: "La pregunta es de opción única (eso es Radio)" },
    ],
    parrafos: [
      "El Checkbutton existe para las decisiones que sí admiten “un poco de todo”: negrita y cursiva; avisos por correo y por la app; extra de queso y extra de salsa. Visualmente es un cuadro que se tacha. Lo importante no es el cuadro, sino que cada marca es independiente. Cuando marcas una, las demás no se apagan. Si el enunciado pide una sola respuesta y tú pones checks, el usuario podrá contradecirse y el programa no sabrá cuál es “la” elección. Leer el problema es clasificar la decisión antes de dibujar. ¿Es una sola? Entonces Radiobutton. ¿Son varias que se acumulan? Entonces Checkbutton. Este párrafo pide esa frontera en una oración. Si la oración no tiene un porque, todavía no hay análisis. Anótenla. Será el centro del mapa. Distinguir radio y check no es un detalle de examen: es la diferencia entre exclusión mutua y acumulación. Un lector atento busca esa frontera. Un lector apresurado pega el control de moda. El mapa debe tener una caja de “sí es check” y otra de “no es check, es radio”.",
      "Cada Checkbutton suele tener su propia variable: BooleanVar o IntVar, a veces con onvalue y offvalue. No comparten un solo canal como los radios. Si les pones la misma variable a todos los checks, dejan de ser independientes: marcar uno altera a los otros de formas extrañas. Leer el diseño es leer qué se comparte y qué no. Aquí no se comparte el canal; se comparte, a lo sumo, el Frame que los agrupa y el título de la pregunta. Con .get() lees si esa marca está activa. Con command= puedes actualizar un Label que liste las combinaciones elegidas. Sin leer cada variable, el programa no sabe qué combinación armó el usuario. Practiquen un ejemplo escolar: “¿Qué extras quieres en el proyecto?”. Cada extra es un check. El resultado no es un único value: es un conjunto. En Canva dibujen un check, su variable, y una flecha a “combinación”. Si dibujan un solo canal para todos, copiaron la lógica del radio y este párrafo no se comprendió. Vuelvan al texto. La independencia es la idea principal.",
      "El estado inicial también importa. ¿Arrancan todos apagados? ¿Hay uno encendido por defecto porque el reglamento lo pide? .set() sirve para eso. Un programa que nace con marcas misteriosas confunde. Un programa que no muestra qué está marcado obliga a adivinar. El Label de resumen —“Elegiste: negrita, cursiva”— es un buen compañero del Checkbutton: hace visible la combinación. Si el Label no cambia al marcar, el clic no dejó huella. Este párrafo pide el viaje del dato: se marca, se guarda en su variable, alguien lee, se muestra la combinación. Cuatro estaciones. Numérenlas en el mapa. Un mapa sin números obliga a improvisar el orden. Relaciónenlo con pasar lista: cada alumno es independiente; el resultado es el conjunto de presentes, no “un solo presente”. Si la analogía se rompe, anoten dónde: esa fisura suele ser el punto difícil. No fuercen la analogía para que todo calce. Reconocer el límite también es análisis.",
      "Errores típicos: usar checks para una pregunta de examen de una sola respuesta; compartir variable entre checks; olvidar leer todas las variables y solo mirar una; no agruparlos en un Frame con un título que diga que se puede marcar más de una. El usuario no adivina tu intención. Si el título dice “elige una” y hay checks, la pantalla miente. Si el título dice “marca todas las que apliquen” y hay radios, también. Leer la pantalla es parte de leer el programa. Listen un error visible y uno invisible. El visible: dos marcas cuando el enunciado pedía una. El invisible: dos checks que parecen independientes y comparten canal. Reparación concreta, no “hay que checarlo”. En la exposición, causa, síntoma y arreglo. Este equipo no entrega depuración genérica. Entrega una lectura del Checkbutton. Los otros colores tienen otro widget. No mezclen el mapa.",
      "Diseñar es decir que no. Si todo es un solo botón de acción, no hace falta un grupo de checks. Si la pregunta no admite combinaciones, este widget sobra. Escriban un ejemplo escolar donde el Checkbutton SÍ aplica y otro donde sería un error. El “no” es tan importante como el “sí”. Quien solo sabe el caso obvio aún no comprende el límite. Los dos ejemplos deben ser concretos: trámite, extras, permisos, formatos que se pueden acumular versus turno único. En el organizador, dos columnas simétricas. Si el “no” se resuelve con “porque no”, no hubo comprensión. Tiene que haber un porque que un oyente pueda repetir. Practiquen esa oración. Irá debajo del título de la lámina. Si no cabe en una oración, todavía está enredada. Sigan recortando. Nombrar el criterio es comprender.",
      "El producto es un solo organizador en Canva. Centro: Checkbutton y combinación. Ramas: variable propia, conjunto de marcas, Label de resumen, sí aplica / no aplica, un error. Cada integrante lee su párrafo largo en voz alta. Luego el equipo dibuja y expone. Cualquier integrante continúa. El salón debe oír cuándo marcar varias y cuándo no. Si al terminar alguien cree que check y radio son “lo mismo, se ven parecidos”, este equipo no enseñó. La semejanza visual es la trampa; la diferencia lógica es la lectura. Defiendan esa diferencia. Canva es el espejo. El texto que leyeron es la fuente.",
    ],
  },
  {
    id: "text",
    nombre: "Text",
    titulo: "Text: el recuadro de muchas líneas",
    mision: "Explicar cuándo usar Text en lugar de Entry y cómo se lee y se escribe su contenido.",
    clave: ["Text", "varias líneas", "get / insert / delete", "wrap"],
    preguntaGuia: "¿Qué se pierde si usas un Entry para un comentario o una redacción?",
    organizador: [
      { caja: "Muchas líneas", hijos: "Widget Text, no Entry" },
      { caja: "Leer", hijos: "get(\"1.0\", \"end-1c\")" },
      { caja: "Escribir", hijos: "insert / delete / wrap=WORD" },
    ],
    parrafos: [
      "El widget Text no es una etiqueta y no es una caja de una sola línea. Es el recuadro donde el usuario escribe un párrafo, un comentario, una justificación, un recado largo. Si el enunciado pide “nombre”, no es Text: es Entry. Si pide “explica por qué”, “pega el código”, “escribe la observación”, sí es Text. Leer el problema es medir cuánto texto cabe en la respuesta. Quien pone un Entry para una redacción obliga al usuario a aplastar ideas. Quien pone un Text para un número de control enseña una caja desproporcionada. Este párrafo pide la frontera en una oración con porque. Anótenla. Centro del mapa. El Text se parece a un cuaderno; el Entry, a un renglón del pase de lista. La analogía ayuda si no se toma al pie de la letra: el programa es un modelo, no el cuaderno. Nombren tres correspondencias: dónde se escribe, cómo se lee después, qué pasa si se deja vacío. Si solo encuentran una, la lectura está incompleta.",
      "Leer el contenido de un Text no es .get() a secas como en un Entry. Se usa get con índices: por convención get(\"1.0\", \"end-1c\") para no arrastrar el salto de línea final. Insertar texto es insert; borrar es delete. wrap=WORD evita que las palabras se partan feo. Estas palabras —índice, get, insert, wrap— son lectura técnica y hay que poder decirlas en español claro: desde dónde hasta dónde copio lo que escribió el usuario; cómo pongo un texto inicial; cómo limpio el recuadro. Sin esa lectura, el botón “Guardar” no guarda o guarda basura. Practiquen el viaje: el usuario escribe varias líneas, alguien lee el bloque, un Label o un archivo recibe el resultado. Si el plan no incluye “leer todo el texto”, el Text es una vitrina. En Canva, una caja de “cómo se lee” con la idea de inicio y fin, no con magia. Un compañero de otro equipo debe poder repetir por qué no basta un get() simple. Esa es la evidencia de comprensión.",
      "El Text vive en un Frame. Una zona titulada “Observaciones” o “Justificación” le da sentido. Sin título, es un rectángulo misterioso. Un Label encima —“Escribe al menos tres líneas”— es instrucción, no adorno. El estado vacío también se diseña: ¿qué pasa si el usuario no escribe nada y pulsa enviar? Un mensaje honesto es mejor que guardar un texto en blanco y fingir que hubo lectura. Este párrafo pide el caso borde. Inclúyanlo en el mapa. Relaciónenlo con una solicitud de permiso: si el motivo va vacío, el trámite no está completo. El programa puede decirlo con un Label. El Text no “sabe” si el texto es suficiente; el programador lee la longitud o el contenido y decide. Comprender el widget es comprender esa responsabilidad. No prometan un corrector de redacción. Prometan una lectura fiel de varias líneas. Modestia inteligente. En la exposición, esa honestidad convence más que una lámina llena de iconos.",
      "Errores: usar Text para una sola palabra; olvidar pack o grid y “no se ve”; leer mal los índices y obtener siempre vacío o un extra raro; insertar cada vez sin borrar y duplicar el texto; no poner wrap y el usuario no entiende el recuadro. Cada error tiene síntoma en pantalla y causa en el código. Listen tres, con reparación concreta. Amárrenlos al Text, no a “depuración”. Un error invisible: get mal recortado. Un error visible: la caja no aparece. En la exposición, causa, síntoma, arreglo. Este equipo no copia una lista de foros. Lee este widget. Los otros colores no leyeron Text. Si su mapa podría ser el de Entry, no recortaron: vuelvan a la idea de varias líneas. Esa es la idea principal. El resto se ordena alrededor.",
      "Un caso mínimo: Frame de encabezado, Label “Comentario”, Text con wrap, botón que lee el bloque y muestra las primeras palabras en un Label de confirmación. Si pueden señalar esas piezas, ya vieron el sistema. El caso debe caber en un minuto. Si es enorme, recorten. Leer para programar es elegir qué sí entra. Colores y diez botones extra pueden esperar. Tres preguntas: ¿cuál es el texto que el usuario produce?, ¿quién lo lee?, ¿qué se muestra después? Todo lo demás es secundario. En Canva, esas tres piezas con flechas numeradas. Si necesitan un párrafo entero para explicar una caja, la caja está mal nombrada. Nombrar bien es comprender. Pónganle nombre propio al caso —“Recado al docente”, “Justificación de retardo”— para que no sea genérico. Lo genérico no se puede analizar.",
      "El producto es un organizador de todo el equipo en Canva. Centro: Text, varias líneas. Ramas: cuándo sí / cuándo Entry, cómo se lee, wrap, un error, el caso mínimo. Cada integrante leyó su párrafo largo en voz alta. Luego dibujan y exponen. Cualquier integrante continúa. El salón debe oír por qué un recuadro de muchas líneas no se trata como un renglón. Si al terminar alguien dice “es lo mismo que Entry pero más grande”, este equipo no enseñó la lectura de índices ni la de la intención. Enseñen la intención primero; los índices después. El mapa es el examen visible de la comprensión. Organicen. Expliquen. No lean otra vez el párrafo como si fuera la exposición: recorran el esquema.",
    ],
  },
  {
    id: "entry",
    nombre: "Entry",
    titulo: "Entry: una sola línea de dato",
    mision: "Explicar qué se captura con Entry, cómo se lee y qué validación mínima necesita.",
    clave: ["Entry", "get / insert / delete", "StringVar", "una línea"],
    preguntaGuia: "¿Qué dato escolar cabe en un Entry y cuál exigiría un Text?",
    organizador: [
      { caja: "Un renglón", hijos: "Entry + Label que nombra el campo" },
      { caja: "Leer", hijos: "get() o textvariable" },
      { caja: "Validar", hijos: "Vacío, tipo, longitud" },
    ],
    parrafos: [
      "El Entry es la caja de una sola línea: nombre, número de control, clave, un dato corto que el usuario teclea. No es un Label —el Label muestra; el Entry captura—. No es un Text —el Text admite párrafo—. Leer el enunciado es medir el dato. Si cabe en un renglón del pase de lista, es Entry. Si es una explicación, no lo es. Este párrafo pide esa frontera con porque. Anótenla. Centro del mapa. Un Entry sin Label al lado es un hueco misterioso: el usuario no sabe qué escribir. El par Label + Entry es una unidad de lectura de la interfaz, como una pregunta y su renglón de respuesta. Quien diseña uno sin el otro deja el texto incompleto. Fomentar la lectura aquí es mirar formularios del plantel: cada campo corto tiene nombre. Traduzcan tres campos a Tkinter. Esa lista ya es material de Canva. Si los tres podrían ser radios, están pensando mal el dato: el Entry es texto o número que el usuario inventa, no una opción de una lista cerrada.",
      "Leer lo escrito es .get(), o una StringVar con textvariable. Insertar un valor inicial es insert o .set() en la variable. Borrar es delete(0, END). Sin leer el Entry, el botón “Continuar” no tiene nada que continuar. El viaje del dato: el usuario teclea, alguien lee, el programa decide —mostrar, guardar, avisar que está vacío—. Cuatro estaciones. Numérenlas. Un mapa sin el “está vacío” finge que el usuario siempre escribe. El caso borde es comprensión. Relaciónenlo con una lista: un renglón en blanco no es un alumno registrado. El programa puede decirlo con un Label. No prometan validar curps perfectas en esta lectura. Prometan una lectura fiel de una línea y una decisión honesta si falta. Modestia. En la exposición, esa honestidad se oye. Practiquen la frase: “el usuario escribe, esto se guarda en X, luego Y lee X”. Si no sale fluida, vuelvan a este bloque. No adelanten Canva con una frase entrecortada.",
      "El Entry vive en un Frame de formulario, casi siempre con grid: una columna de Labels y una de cajas, fila por campo. pack también puede apilar pares, pero el formulario se lee mejor en filas. No mezclen pack y grid en el mismo Frame. La regla es del padre, no del Entry. Este párrafo conecta el widget con el acomodo, sin robarle el tema al equipo de Frame: ustedes solo necesitan saber que el Entry tiene un padre y un idioma. Si “no se ve”, pregunten dónde vive y con qué se acomodó. Tres preguntas antes de tocar código. Llévenlas al mapa como protocolo. Un objeto sin zona no se usa, aunque “exista”. La analogía del casillero: el renglón tiene número y nombre. El Entry tiene Label y geometría. Si no pueden contar este error sin jerga, relean. Está escrito para enseñarlo.",
      "Errores: usar Entry para un párrafo; no leer get() y fingen que ya capturaron; no validar vacío; show=\"*\" mal entendido si no es una contraseña; olvidar que get() devuelve texto y luego comparan con un número sin convertir. Cada error, síntoma y causa. Tres fallos, tres arreglos concretos. Amárrenlos al Entry. Un error visible: la caja no aparece. Un error invisible: comparan \"1\" con 1 y “nunca entra”. En la exposición, no digan “hay que checarlo”. Digan la línea de decisión. Este equipo leyó Entry. El de Text leyó varias líneas. Si sus mapas se parecen, recorten: una línea versus párrafo. Esa es la idea principal. El resto se ordena alrededor.",
      "Un caso mínimo: Label “Número de control”, Entry, botón que lee y muestra el dato en otro Label, o avisa “Falta el número”. Cabe en un minuto. Si el caso es enorme, recorten. ¿Cuál es el dato?, ¿quién lo lee?, ¿qué se muestra si falta? Tres piezas. Nombren el caso —“Pase de lista”, “Búsqueda de alumno”— para que no sea genérico. Lo genérico no se analiza. En Canva, flechas numeradas. El Entry al centro del formulario, no de toda la ventana. Un Frame de encabezado puede existir, pero no es el tema de ustedes: menciónenlo y dejen el análisis profundo al equipo de Frame. Respetar el recorte también es lectura: idea principal versus secundaria. La principal es capturar una línea. Defiéndanla.",
      "El producto es un organizador de todo el equipo. Centro: Entry, una línea. Ramas: Label compañero, get, vacío, caso mínimo, un error, diferencia con Text. Cada integrante lee su párrafo largo en voz alta. Luego Canva y exposición. Cualquier integrante continúa. El salón debe oír qué dato cabe en un renglón y qué no. Si alguien sale pensando que Entry y Text son “lo mismo”, no comprendió la medida del dato. Enseñen la medida. El mapa es el examen visible. Organicen. Expliquen. No copien el widget del color de al lado: cada columna leyó el suyo.",
    ],
  },
];

export function widgetTemaForTeam(teamIndex: number): WidgetTema {
  const list = TKINTER_WIDGET_TEMAS;
  return list[((teamIndex % list.length) + list.length) % list.length]!;
}

export function productoWidget(nombre: string) {
  return `Con la lectura que acaban de hacer, TODO el equipo analiza y comprende el widget «${nombre}» y lo plasma en UN SOLO organizador gráfico o mapa cognitivo en Canva (PowerPoint o Google Drawings también sirven). El mapa tiene que nacer de los párrafos, no de un tutorial. No es un trabajo por persona: es uno por equipo. Cada columna leyó un widget distinto: no copien el mapa de otro color.`;
}

export function bloqueDesdeWidget(tema: WidgetTema, memberCount: number) {
  const parrafos = assignParagraphs(tema.parrafos, Math.max(1, memberCount));
  return {
    titulo: tema.titulo,
    mision: `Cada integrante lee EN VOZ ALTA su párrafo largo sobre ${tema.nombre}. Escuchen, analicen y comprendan. Luego el equipo entero arma un solo mapa en Canva y lo expone.`,
    texto: parrafos.join("\n\n"),
    parrafos,
    clave: tema.clave,
    preguntaGuia: tema.preguntaGuia,
    producto: productoWidget(tema.nombre),
    organizador: tema.organizador,
  };
}
