export type GeneratedBloque = {
  titulo: string;
  mision: string;
  texto: string;
  parrafos: string[];
  clave: string[];
  preguntaGuia: string;
  producto: string;
  organizador: Array<{ caja: string; hijos: string }>;
};

const ANGLES = [
  "que_es",
  "analogia",
  "como_se_usa",
  "errores",
  "caso",
  "diseno",
  "relacion",
  "cierre_practica",
] as const;

const METAPHORS = [
  "un recetario de cocina",
  "un tablero de fútbol con zonas",
  "una mochila con compartimentos",
  "un examen de opción única",
  "un semáforo en un cruce",
  "un cajón de herramientas",
  "un mapa del salón",
  "una fila en la cafetería",
];

function hashSeed(input: string) {
  let h = 2166136261;
  for (let i = 0; i < input.length; i += 1) {
    h = Math.imul(h ^ input.charCodeAt(i), 16777619);
  }
  return h >>> 0;
}

function pick<T>(list: T[], seed: number, salt: number) {
  return list[(seed + salt * 17) % list.length]!;
}

function cleanTopic(raw: string) {
  return raw.replace(/\s+/g, " ").trim().slice(0, 180);
}

/** Reparte la lectura: un párrafo extenso por integrante. Nunca parte un párrafo en frases sueltas. */
export function assignParagraphs(parts: string[], memberCount: number): string[] {
  const n = Math.max(1, memberCount);
  const source = parts.map((p) => p.trim()).filter(Boolean);
  if (!source.length) return Array.from({ length: n }, () => "");
  if (source.length === n) return source;
  if (source.length < n) {
    const out = [...source];
    while (out.length < n) out.push(source[out.length % source.length]!);
    return out.slice(0, n);
  }
  const buckets: string[][] = Array.from({ length: n }, () => []);
  source.forEach((p, i) => {
    const idx = Math.min(n - 1, Math.floor((i * n) / source.length));
    buckets[idx]!.push(p);
  });
  return buckets.map((b) => b.join(" "));
}

function productCopy(topic: string) {
  return `Con la lectura que acaban de hacer, TODO el equipo analiza y comprende «${topic}» y lo plasma en UN SOLO producto: un organizador gráfico o mapa cognitivo. Háganlo en Canva (PowerPoint o Google Drawings también sirven) y expónganlo frente al grupo. El mapa tiene que nacer de los párrafos, no de un resumen copiado. No es un trabajo por persona: es uno por equipo.`;
}

function sixParagraphs(
  topic: string,
  metaphor: string,
  week: number,
  n: number,
  of: number,
  angle: (typeof ANGLES)[number],
): string[] {
  const t = topic;
  const m = metaphor;
  if (angle === "que_es") {
    return [
      `El tema de esta lectura es «${t}». No es un adorno para el examen ni una etiqueta que se memoriza la noche anterior: es una idea que organiza cómo se escribe, se lee y se explica un programa. Quien no puede nombrarlo con sus palabras todavía no lo domina, aunque haya copiado diez ejemplos. Leer, en informática, no es pasar la vista por el código: es reconstruir la intención del autor y el problema del usuario. Por eso este párrafo pide algo más que un título. Pide que el equipo se detenga y se pregunte qué fenómeno del mundo real está intentando ordenar «${t}». Si esa pregunta no se responde, el resto de la sesión se vuelve un copiar-pegar sin comprensión. Un concepto bien leído se puede enseñar a alguien que no programó; un concepto mal leído solo se “ve” cuando el programa ya falló. Antes de seguir, cada integrante debería poder decir en una oración qué es «${t}» y para qué existe. Esa oración no se improvisa: se extrae de la lectura. Anótenla, porque será el centro del organizador gráfico. Si al terminar este párrafo nadie puede repetir la idea sin mirar la pantalla, hay que volver a leerlo. Fomentar la lectura aquí significa resistir la prisa de “ya entendí” y exigir evidencia de comprensión.`,
      `Toda idea de interfaz nace de un problema que el usuario ya trae encima. Con «${t}» hay que preguntarse qué necesidad cubre y qué pasaría si esa pieza no existiera en la ventana. Un programa no se diseña porque “así lo trae el tutorial”: se diseña porque alguien tiene que elegir, agrupar, confirmar o entender algo. Si quitas «${t}» y la interfaz sigue siendo igual de clara, entonces no era esencial; si al quitarlo el usuario se pierde, entonces sí organiza la experiencia. Esa prueba mental es análisis, no adorno. Imaginen a un compañero que nunca ha visto el tema: ¿podría explicar, solo con lo que oye ahora, qué dolor evita esta herramienta? Si la respuesta es vaga, el equipo todavía está en la superficie. La comprensión se nota cuando pueden dar un ejemplo escolar —pasar lista, elegir turno, entregar un archivo, armar un examen— y señalar dónde interviene «${t}». No basta con decir “sirve para la interfaz”. Hay que decir a quién le sirve, en qué momento y con qué consecuencia si falta. Esas tres flechas (quién, cuándo, si falta) ya son material del mapa cognitivo. Lean despacio: el objetivo no es terminar el párrafo, es poder defenderlo frente al grupo.`,
      `También hay que decir qué NO es «${t}». Los conceptos de interfaz se prestan a confusiones porque se parecen en la pantalla y se distinguen en la lógica. Si mezclas dos ideas, el usuario cree que eligió una cosa y el programa ejecuta otra. Esa distancia entre lo que se ve y lo que ocurre es, casi siempre, un error de lectura previa: nadie se detuvo a separar términos. Un lector atento busca fronteras. Pregunten: ¿con qué se confunde este tema?, ¿qué haría un principiante si solo mira el dibujo y no el código?, ¿qué palabra del enunciado cambia por completo la herramienta que conviene usar? Distinguir no es ser quisquilloso; es comprender. En un organizador gráfico esas fronteras se vuelven cajas distintas, no un solo globo con todo adentro. Si en el mapa de Canva «${t}» aparece pegado a otra idea sin flecha que las separe, la lectura no se comprendió: se resumió. Este párrafo pide precisamente eso: una lista breve de “sí es / no es / se parece pero no”. Tres contrastes bastan, siempre que salgan del texto y no de la memoria. Al terminar, el equipo debería poder corregir a alguien que use el término de forma floja.`,
      `Para anclar la idea, compárenla con ${m}. En el mundo real nadie tira todas las piezas en un solo montón y espera que el trabajo salga limpio: hay contenedor, hay partes que van adentro y hay reglas para no revolverlas. En el código esas reglas se ven tanto como en la pantalla. La analogía no es un juego: es un instrumento de comprensión. Si pueden señalar, en ${m}, cuál sería el contenedor, cuál la opción, cuál la señal y cuál la acción, entonces ya están leyendo arquitectura, no decoración. Si la analogía se rompe, anoten dónde se rompe: esa fisura suele ser el punto difícil del tema. Un mapa cognitivo se construye con esas correspondencias. Mundo real → programa. Una flecha que no se puede explicar es una flecha de adorno. Por eso este equipo no va a dibujar “bonito”; va a dibujar verdadero. Lean otra vez la comparación y busquen tres correspondencias, no una. Si solo encuentran una, la lectura todavía está incompleta. La sesión ${week} pide evidencia de análisis, no velocidad.`,
      `Este equipo es el ${n} de ${of} y su recorte no es el de la columna de al lado. Eso no es casualidad: leer en el aula también es defender una mirada sin copiar la del vecino. Si dos equipos entregan el mismo mapa, no hubo comprensión: hubo contagio. Usen un ejemplo del salón —una lista, un recado, un permiso, un examen, un archivo— que solo ustedes puedan explicar. La lectura se vuelve propia cuando el ejemplo no cabe en otra columna. Al mismo tiempo, no inventen fuera del texto: el ejemplo tiene que nacer de «${t}», no de un tema anterior que ya dominan y les da flojera dejar. Un lector honesto admite lo que aún no entiende. Si hay una frase de este párrafo que no pueden parafrasear, márquenla: esa frase es la que debe aparecer, aclarada, en el organizador. Comprender no es repetir. Comprender es poder enseñar. Cuando expongan, cualquier integrante debería poder tomar la lámina y continuar. Si solo “el que dibuja” sabe qué hay en Canva, el equipo no leyó junto: uno copió y los demás esperaron.`,
      `Cierren este bloque con una definición de una oración y con una pregunta de comprensión. La definición alimenta el centro del mapa; la pregunta alimenta las flechas. Una buena pregunta no se responde con “sí” o “no”: obliga a relacionar. Por ejemplo: si «${t}» desapareciera, ¿qué parte de la ventana dejaría de tener sentido y qué parte seguiría igual? Esa distinción demuestra que leyeron con análisis. No copien la pregunta guía del encabezado: inventen una que solo se pueda responder después de haber oído todos los párrafos. Luego, en Canva, esa pregunta se vuelve una caja o una flecha, no un título decorativo. Recuerden el objetivo de la sesión: fomentar lectura, análisis y comprensión, y plasmarlas en un organizador. Si el producto se puede hacer sin haber leído, está mal planteado. Si para armarlo necesitan volver al texto, está bien: eso es leer para pensar. Antes de pasar al siguiente integrante, el equipo debe tener ya tres palabras clave y la definición. Sin eso, el mapa nacerá vacío.`,
    ];
  }
  if (angle === "analogia") {
    return [
      `Piensa «${t}» como ${m}. En la vida diaria nadie deja todas las herramientas en un solo montón y espera que el trabajo salga limpio: hay zonas, hay turnos y hay señales que evitan el caos. Esa imagen no es un adorno para “hacer amena la clase”. Es una estrategia de lectura. Cuando un concepto de programación se vuelve abstracto, la analogía permite reconstruirlo con piezas que ya entendemos. El riesgo es tomarla al pie de la letra y olvidar que el programa no es el mundo real: es un modelo. Leer bien es ir y volver entre los dos lados. ¿Qué parte de ${m} se parece al contenedor? ¿Qué parte se parece a la opción que no admite “un poco de todo”? ¿Qué parte se parece al aviso que el usuario recibe cuando elige? Si no pueden responder esas tres preguntas, todavía no leyeron: solo oyeron una comparación bonita. Este párrafo pide que el equipo se detenga y nombre las correspondencias en voz alta. Nombrar es comprender. Lo que no se puede nombrar no se puede dibujar en el organizador. Anoten las tres piezas ahora, aunque después las corrijan. La lectura extensa sirve para eso: dar tiempo a que la idea se acomode, no para terminar rápido y pasar a Canva vacío.`,
      `En la interfaz ocurre lo mismo que en ${m}: un control no adivina tu intención. Tú lo agrupas, lo nombras y le das un valor. Si no hay agrupación, la analogía se rompe y el usuario se pierde. Muchos programas “sí corren” y, al mismo tiempo, mienten: parecen preguntar una cosa y guardan otra. Eso no se arregla con más botones; se arregla leyendo el diseño. La lectura de una interfaz pregunta quién contiene a quién, qué se comparte y qué queda fuera. Si dos elementos parecen del mismo grupo y no lo son, el usuario aprende una regla falsa. Si parecen distintos y sí lo son, también. Por eso este párrafo insiste en las palabras agrupar, nombrar y valorar. Son tres operaciones de pensamiento, no tres líneas de código. En el organizador gráfico esas operaciones se vuelven nodos. Un mapa que solo dice «${t}» en el centro, sin esas tres ramas, es un mapa de título, no de comprensión. Lean otra vez y busquen en el salón un objeto que se agrupa, se nombra y se valora —una lista, un casillero, un semáforo, una fila—. Traigan ese objeto al mapa. Si no pueden explicarlo sin leer este párrafo otra vez, todavía falta análisis. Está bien volver al texto: eso es lectura, no fracaso.`,
      `Hay un fallo típico que la analogía ayuda a ver. Si dos grupos distintos usan la misma señal, el usuario cree que eligió una cosa y el programa escucha otra. Eso también pasa cuando se copia mal una variable, cuando dos equipos de controles comparten lo que no deberían, o cuando el nombre en pantalla no coincide con el valor interno. Leer es sospechar de esas coincidencias. Un lector principiante mira el dibujo; un lector que analiza mira las conexiones invisibles. Pregunten: ¿qué sería “la misma señal” en ${m}? ¿Un silbato usado para dos juegos distintos? ¿Una luz que significa dos cosas? Cuando encuentren esa imagen, ya tienen el error conceptual del tema. No lo dejen solo en la conversación: llévenlo al organizador como una caja de “error si…”. El mapa cognitivo no es un resumen amable: también enseña trampas. Si el producto en Canva no incluye al menos un malentendido posible, el equipo comprendió a medias. Este párrafo, por tanto, no se “termina” al oírlo. Se termina cuando el equipo puede contar una anécdota —real o inventada con cuidado— donde la señal duplicada cause un problema. Esa anécdota es evidencia de comprensión.`,
      `Den un paso atrás y conviertan la analogía en un esquema. ¿Qué parte de ${m} sería el contenedor, cuál la opción exclusiva y cuál el botón que pregunta? No basta con señalar con el dedo: hay que justificar. El contenedor agrupa y no “hace” la tarea del usuario; la opción exclusiva impide elegir dos verdades a la vez; el botón que pregunta lee el resultado y decide. Si mezclan esos papeles, el mapa se vuelve un nudo. La comprensión se demuestra cuando las flechas tienen dirección: de contenedor a hijos, de hijos a valor, de valor a respuesta. Un organizador sin direcciones es una nube de palabras. Por eso este párrafo es más lento. Pide que el equipo discuta y no que el más rápido dibuje. Si hay desacuerdo, mejor: el desacuerdo obliga a volver al texto. Lean la analogía otra vez y busquen una frase que dé la razón a uno y no al otro. Esa es lectura crítica. En la exposición, no digan “es como ${m}” y ya. Digan qué parte corresponde a qué, y qué parte de la analogía no se debe forzar. Reconocer el límite de una comparación también es comprender.`,
      `Esta analogía es de este equipo: sesión ${week}, el ${n} de ${of}. El equipo de al lado tiene otra a propósito. No la mezclen ni la “mejoren” copiando. Leer en grupos distintos sirve para que el salón oiga varias puertas de entrada al mismo tema, no para producir seis láminas idénticas. Si su mapa podría colgarse en otra columna sin que nadie note el cambio, no hubo apropiación del texto. Usen un detalle del salón —un reglamento, una fila, un color de butaca, un trámite— que amarre ${m} con «${t}». Ese detalle es de ustedes. Al mismo tiempo, no se vayan por la anécdota y olviden el concepto: la analogía es un puente, no el destino. El destino es explicar «${t}» con precisión. Un oyente de otro equipo debería poder decir, al final, qué aprendió de ustedes que no estaba en su propia lectura. Eso exige haber leído con atención lo propio y no haber espiado lo ajeno. Anoten desde ahora el título de su lámina. Si el título es solo el nombre del tema, es débil. Si el título nombra la analogía y el concepto, ya hay análisis.`,
      `Anoten tres flechas mundo-real → programa. Esas flechas son el esqueleto del organizador gráfico que harán en Canva. Cada flecha debe poder decirse en una oración completa, no en una palabra suelta. Por ejemplo: “la zona de ${m} corresponde al contenedor porque agrupa sin ejecutar la tarea”. Si no pueden terminar la oración con un porque, la flecha es decorativa. Este cierre pide evidencia de comprensión, no velocidad. Antes de abrir Canva, el equipo recita las tres flechas sin mirar el párrafo. Quien no pueda recitarlas vuelve a leer. Así se fomenta la lectura: con una exigencia clara de lo que hay que entender, no con un resumen de dos líneas. El producto único del equipo nacerá de esas flechas, de la analogía y de un error posible. Si al exponer solo leen este texto otra vez, el organizador no sirvió. El organizador tiene que dejarlos hablar sin el párrafo delante. Ese es el criterio. Lean, analicen, comprendan y recién entonces dibujen. Canva no piensa por ustedes; ustedes piensan y Canva lo muestra.`,
    ];
  }
  if (angle === "como_se_usa") {
    return [
      `Usar «${t}» no es copiar un tutorial de memoria. Hay un orden, y si lo saltas el programa “no jala” o, peor, jala y miente. Quien pega líneas sin leerlas termina con una ventana que parece terminada: botones que no aparecen, opciones que no se apagan, mensajes que no coinciden con lo que el usuario eligió. El tutorial muestra el qué; esta lectura obliga a preguntar el porqué de cada paso. Si no puedes explicar en voz alta qué nace primero y qué se prueba al final, todavía no usas el tema: solo lo imitas. Por eso este párrafo es largo a propósito. Fomentar la lectura aquí significa resistir la tentación de “ya vimos un video”. Un procedimiento se comprende cuando se puede reconstruir sin la receta delante, igual que se comprende un texto cuando se puede contar con otras palabras. El equipo debe salir de este bloque con una secuencia, no con una impresión. Anoten, aunque sea en sucio, los pasos que creen oír. Luego los contrastarán con los párrafos siguientes. Si los pasos no se pueden dibujar en un organizador, aún no se comprendieron. La sesión no pide código todavía: pide una lectura del método. Quien no lee el método, programa a ciegas.`,
      `El primer movimiento casi siempre es el mismo: nace el contenedor. Después nacen los controles hijos. Si el hijo no tiene padre claro, no sabes dónde vive, y entonces no sabes ni acomodarlo ni agruparlo ni leerlo. En programación de interfaces, “dónde vive” no es una metáfora poética: es una relación de pertenencia. Leer esa relación es leer arquitectura. Un error frecuente es crear el control y olvidar sentarlo en su caja, o sentarlo en la ventana cuando debía ir en un grupo, o crear el grupo después de haber llenado la ventana de piezas sueltas. El orden no es capricho del lenguaje: es la lógica de quién contiene a quién. Compárenlo, si les ayuda, con ${m}: primero el continente, luego lo que va adentro, nunca al revés si quieren que el conjunto se entienda. Este párrafo pide que el equipo pueda explicar, a alguien que no programa, por qué el contenedor va primero. Si la explicación usa solo jerga, no hubo comprensión. Si usa un ejemplo del salón —una caja, una lista, una zona del pizarrón—, hubo lectura. Lleven al mapa una flecha etiquetada “primero el contenedor”. Sin esa flecha, el resto de los pasos flota.`,
      `Luego se acomodan las piezas con un solo gestor de geometría por caja. Mezclar pack y grid en el mismo padre es el error más común, y se parece a hablar dos idiomas en la misma oración: cada palabra puede ser correcta y el conjunto resulta ilegible. Leer un diseño es leer ese idioma. ¿Esta caja apila? ¿Esta otra usa filas y columnas? ¿Hay alguna que se obstine en coordenadas fijas? No se trata de memorizar nombres: se trata de comprender que cada contenedor habla de una sola manera. Si el equipo no puede decir qué idioma usaría para un encabezado, para un formulario y para un bloque de botones, todavía está copiando recetas. Analicen un caso mínimo. Una ventana puede usar un idioma para colocar tres zonas, y cada zona puede usar otro idioma por dentro. Eso no es mezclar: es respetar el padre de cada hijo. La mezcla prohibida es dentro del mismo padre. Esa distinción —parece un detalle, es el corazón— debe aparecer en el organizador como dos cajas: “sí se puede” y “no se puede”. Si el mapa no las separa, la lectura de este párrafo no se comprendió. Vuelvan al texto y extraigan un ejemplo de cada lado.`,
      `Después se conectan a una variable o a un evento. Sin esa conexión, el clic no deja huella: la pantalla se mueve y el programa no se entera. Muchos estudiantes creen que “ya está” cuando ven el control. La lectura atenta pregunta qué se comparte entre controles y qué función se dispara al cambiar. El valor, el canal y la respuesta son tres ideas distintas. Si las juntan en una sola palabra, el mapa miente. Una variable compartida hace que un grupo se comporte como grupo; un valor distinto permite reconocer la elección; un evento convierte esa elección en una acción. Si falta una de las tres, el usuario elige en el aire. Este párrafo pide un análisis lento. Tomen «${t}» y señalen, en voz alta, dónde está el canal, dónde el valor y dónde la respuesta. Si no los encuentran, no inventen código: formulen la pregunta que el mapa deberá resolver. Comprender también es saber qué todavía no se sabe. En Canva, dibujen esas tres piezas con flechas, no como adornos alrededor del título. Un oyente de otro equipo debería poder repetirlas después de su exposición. Si no puede, el organizador no enseñó: solo decoró.`,
      `Al final alguien lee el resultado. Si nadie pregunta qué eligió el usuario, el programa no decide nada: es una vitrina. Leer el resultado es tan parte de «${t}» como crearlo. Un botón que no consulta, una etiqueta que no cambia, un mensaje que siempre dice lo mismo, son síntomas de una lectura incompleta del flujo. El análisis consiste en seguir el dato desde que nace hasta que se usa. ¿Dónde se crea? ¿Dónde se modifica? ¿Dónde se interpreta? Esas tres estaciones caben en un organizador de flujo. Si el equipo solo dibuja “ventana bonita”, no comprendió este párrafo. Imaginen que tienen que explicar el programa a un director que no va a ver el código. Tendrían que decir: el usuario elige, el programa guarda, alguien pregunta, se muestra una respuesta. Si no pueden llenar esas cuatro casillas con palabras de «${t}», vuelvan a leer. La comprensión se demuestra cuando el flujo se puede contar en orden y cuando se puede decir qué pasaría si se omite el último paso. Anoten ese “qué pasaría si…”. En la exposición, esa consecuencia suele ser lo que el salón más recuerda.`,
      `Ensayen el orden en voz alta, de principio a fin, sin saltarse a quien le toca leer. Con esa cadena ya pueden dibujar el flujo en Canva y exponerlo. El producto no es un collage de iconos: es la prueba de que leyeron un procedimiento y lo comprendieron. Cada caja del mapa debe nacer de un paso de esta lectura: contenedor, acomodo, conexión, lectura del resultado. Si una caja no se puede apuntar a un párrafo, sobra. Si un párrafo no dejó caja, faltó análisis. Este cierre es deliberadamente exigente porque el objetivo de la sesión es fomentar lectura, no llenar minutos. Antes de abrir la herramienta digital, el equipo recita el orden. Quien se trabe vuelve a su párrafo. Nadie “se salva” dibujando bonito. En la exposición, cualquier integrante toma la lámina y recorre las flechas. El ${n} de ${of}, sesión ${week}, no entrega un resumen de internet: entrega una lectura propia de cómo se usa «${t}». Si el mapa se entiende sin el texto delante, la comprensión ocurrió. Si para explicarlo necesitan leer otra vez cada renglón, el organizador todavía no está listo: hay que volver al análisis, no a copiar más.`,
    ];
  }
  if (angle === "errores") {
    return [
      `Hay lecturas de código que ahorran veinte minutos de “no jala”. Con «${t}» conviene cazar errores antes de ejecutar, porque ejecutar sin haber leído es apostar. Un programa puede arrancar y, aun así, estar conceptualmente roto: el usuario ve una cosa, el valor interno es otra, el mensaje no corresponde. Ese tipo de fallo no siempre lanza una excepción vistosa. Por eso la lectura crítica es parte del oficio y no un lujo de quien “ya sabe”. Este párrafo pide un cambio de hábito. En vez de preguntar “¿cómo lo pongo?”, pregunten “¿qué malentendido produciría si lo pongo mal?”. Esa segunda pregunta es análisis. Hace que el equipo busque causas, no culpables. Hace que el organizador gráfico tenga una rama de errores, no solo de definiciones. Lean con sospecha productiva. Cada frase de esta lectura debería dejar una trampa posible y una forma de detectarla. Si al terminar solo tienen una lista de consejos genéricos —“hay que poner atención”— no comprendieron. La comprensión de un error es concreta: se ve en la pantalla, se ve en el código, o se ve en lo que el usuario cree. Anoten desde ahora esa triple clasificación. Les servirá en el mapa.`,
      `Un clásico: crear controles sin padre claro, o crearlos y olvidar mostrarlos. El widget existe, pero nadie lo sentó en la ventana. Quien no ha leído el procedimiento culpa al lenguaje; quien sí lo leyó pregunta dónde vive cada pieza. “No se ve” no es un misterio: es una consecuencia. O no tiene contenedor, o no tiene geometría, o está detrás de otra cosa, o se creó y se abandonó. El análisis consiste en no aceptar “no jala” como diagnóstico. Este párrafo invita a reconstruir la escena. Imaginen que un compañero dice que su opción “no aparece”. ¿Qué tres preguntas harían antes de tocar una línea? Esas preguntas son comprensión convertida en método. Llévenlas al organizador como un pequeño protocolo. Un mapa cognitivo puede tener una caja que diga “si no se ve, preguntar…” y tres flechas. Eso enseña más que un icono de error. Relaciónenlo, si les ayuda, con ${m}: un objeto que existe pero no está en su zona no puede usarse, aunque “esté” en alguna parte. La analogía no reemplaza al concepto; lo hace explicable frente al grupo. Si no pueden contar este error sin jerga, vuelvan a leer el párrafo. Está escrito para poder enseñarlo.`,
      `Otro error de lectura: mezclar pack y grid en la misma caja, o no compartir la variable en un grupo de opciones. La pantalla miente. Puede mostrar dos marcas, ninguna, o un acomodo que “se sale” sin que el programador entienda por qué. Estos fallos son conceptuales. No se resuelven con más líneas: se resuelven comprendiendo que un padre habla un solo idioma de acomodo y que un grupo comparte un canal. Si cada control tiene su propio canal, dejan de ser grupo aunque se vean juntos. Si dos idiomas pelean por el mismo padre, el conjunto se vuelve ilegible. Este párrafo pide que el equipo separe esos dos errores, porque se parecen en el fastidio y no en la causa. En el organizador deben ser dos cajas, no una. Un lector que analiza no agrupa por el enojo que le provocan las cosas: agrupa por la lógica. Inventen un síntoma visible para cada error y un síntoma que solo se vea en el código. Esa doble mirada —pantalla y texto— es exactamente la comprensión que esta sesión busca. Si el mapa solo dice “no mezclar” y “usar una variable”, es un letrero, no un análisis.`,
      `También se repite el mismo valor en dos opciones, o la interfaz arranca en blanco sin valor inicial. El usuario no sabe qué está elegido, o cree haber elegido y el programa no distingue. Leer el diseño incluye leer el estado al arrancar. Un programa que nace “en silencio” obliga al usuario a adivinar. Un programa que usa el mismo valor dos veces obliga al programa a no poder distinguir. Ambos son fallos de comprensión del enunciado: no se leyó qué decisión se estaba modelando. Pregunten qué decisión modela «${t}» en un ejemplo escolar. Si la decisión admite dos verdades a la vez, quizá el control está mal elegido. Si admite una sola y aun así se puede marcar doble, el grupo está mal armado. Este párrafo conecta error con intención. El organizador debe tener una caja de “estado inicial” y otra de “valores distintos”. Sin ellas, el equipo memorizó síntomas y no causas. Antes de seguir, parafraseen este bloque con un trámite del plantel: inscripción, turno, materia, formato de entrega. Si el trámite no encaja, elijan otro. El esfuerzo de traducir es el análisis. Lo que no se puede traducir, aún no se comprendió.`,
      `Un error se ve en la pantalla: un hueco, dos marcas, un botón invisible, un texto que no cambia. Otro solo se ve en el código: dos variables que parecen un grupo y no lo son, un valor repetido, un padre con dos idiomas. La lectura experta mueve la mirada de un lado al otro. Este párrafo pide que el equipo construya una tabla mental de “se ve / no se ve”. Esa tabla es oro para el mapa cognitivo. En Canva pueden hacer dos columnas, no un sol con rayos. El objetivo no es que el producto se vea “de feria”: es que organice el pensamiento. Si al exponer no pueden dar un ejemplo de error invisible y uno visible, la lectura quedó a medias. Relacionen cada ejemplo con «${t}», no con un tema genérico de “depuración”. La precisión demuestra comprensión. Un oyente de otra columna debería salir diciendo: “ahora sé qué mirar antes de ejecutar”. Esa frase es el indicador de que este equipo leyó para enseñar, no para ocupar el turno. Anoten los ejemplos ahora. No los dejen para “ya en Canva”, porque en Canva la prisa borra matices.`,
      `Listen tres fallos —de pantalla o de código— y una reparación de una línea o de una decisión de diseño. Eso entra al mapa cognitivo del equipo en Canva. La reparación tiene que ser tan concreta que se pueda decir en voz alta sin teatro. “Hay que checarlo” no es reparación. “Este padre no puede mezclar dos gestores” sí lo es. “Este grupo necesita un solo canal y valores distintos” también. Este cierre convierte la lectura en producto. Si los tres fallos se podrían colgar en cualquier otro tema, son demasiado vagos: vuelvan al texto y amárrenlos a «${t}». El ${n} de ${of}, sesión ${week}, no entrega una lista de errores de internet. Entrega una lectura analizada. En la exposición, no lean otra vez los párrafos: señalen el mapa y cuenten causa, síntoma y arreglo. Quien no pueda hacerlo vuelve a su párrafo. Así se fomenta la comprensión: con una exigencia pública y compartida, no con un dibujo que nadie explica. El organizador es de todos. El análisis también.`,
    ];
  }
  if (angle === "caso") {
    return [
      `Caso de esta semana: una ventana corta que usa «${t}» de verdad, no de adorno. Si el caso es enorme, recórtelo. Leer para programar es elegir qué sí entra y qué se queda fuera. Un caso didáctico no pretende impresionar: pretende poder explicarse. Si para contarlo necesitan cinco minutos de preámbulo, todavía no lo comprendieron: lo están cubriendo de detalles. Este párrafo pide un recorte consciente. ¿Cuál es la decisión del usuario? ¿Cuál es la zona que la contiene? ¿Cuál es la respuesta del programa? Tres preguntas, tres piezas. Todo lo demás —colores, logotipos, diez botones extra— puede esperar. Un lector que analiza recorta. Un lector que se pone nervioso acumula. El objetivo de la sesión es comprensión, no copiar un sistema real completo. Relacionen el caso, si les sirve, con ${m}: un conjunto pequeño, con zonas claras, que se puede señalar con el dedo. Si no pueden dibujarlo de memoria en el pizarrón, el caso sigue grande. Anoten el recorte ahora. Ese recorte será el título honesto de su lámina en Canva.`,
      `Arriba, un encabezado. Abajo, una pregunta que no admite “un poco de todo”. Esa pregunta obliga a una sola decisión, y esa obligación es el corazón del caso. Muchas interfaces fallan porque preguntan dos cosas a la vez o porque no preguntan nada y esperan que el usuario adivine. Leer el enunciado de un programa es decidir qué se está preguntando. Si la pregunta admite combinaciones, el control cambia. Si admite una sola respuesta, el grupo debe comportarse como grupo. Este párrafo insiste en leer la pregunta antes de dibujar la ventana. El encabezado no es adorno: sitúa al usuario —materia, nombre, propósito—. La pregunta no es texto de relleno: es el problema que «${t}» viene a resolver. En el organizador, esas dos zonas son cajas distintas. Si las fusionan, el mapa miente sobre la arquitectura. Inventen la pregunta con un trámite escolar. Tiene que poder leerse en voz alta y entenderse sin código. Si al oírla un compañero de otro equipo no sabe qué se le está pidiendo, la pregunta está mal escrita. Reescríbanla. Eso también es lectura: revisar el texto hasta que signifique.`,
      `A un lado, una acción que lee la elección y responde. Si pueden señalar contenedor, grupo, canal y evento, ya pueden programarlo después. El caso se vuelve creíble cuando el dato viaja: se elige, se guarda, se pregunta, se muestra. Si alguna estación falta, el caso es una maqueta hueca. Este párrafo pide que el equipo recorra ese viaje en voz alta, despacio, como quien lee un cuento y no quiere perder el hilo. ¿Quién elige? ¿Dónde se nota la elección? ¿Quién pregunta? ¿Qué se muestra si acertó y qué si no? Esas cuatro respuestas son análisis. No las resuelvan con “un botón”. El botón es el actor visible; la comprensión está en lo que el botón hace. En Canva, dibujen el viaje con flechas numeradas. Un mapa sin números obliga al expositor a improvisar el orden, y entonces el salón se pierde. Relacionen cada estación con «${t}», no con un programa genérico. La precisión es la prueba de que leyeron este caso y no “un caso cualquiera de interfaz”. Si no pueden numerar, vuelvan al párrafo. El orden es el texto.`,
      `El caso debe caber en un minuto de explicación. Si se parece al de otro equipo, cámbienlo con ${m} o con un trámite escolar que solo ustedes puedan defender. La originalidad aquí no es vanidad: es evidencia de comprensión. Quien comprende puede cambiar el ejemplo sin perder la estructura. Quien solo copió no puede cambiar nada porque no sabe qué es esencial. Pregunten qué pueden cambiar —el texto de la pregunta, el número de opciones, el mensaje final— y qué no pueden cambiar —la idea de un solo canal, de un contenedor, de una lectura del resultado—. Esa frontera es el análisis más valioso del bloque. Llévenla al organizador como “se puede variar / no se puede variar”. En la exposición, esa caja suele generar las mejores preguntas del docente. No la dejen para el final. Este equipo es el ${n} de ${of} en la sesión ${week}: su caso no puede ser el eco del de al lado. Si al mirar otra columna sienten que “está igual”, recorten o cambien el contexto, no el concepto.`,
      `Leer para programar es ver el sistema antes de teclearlo. Cada párrafo de esta lectura es una pieza de ese sistema, no un adorno que se ignora para ir “a lo práctico”. Lo práctico, en esta sesión, es el organizador: ahí se nota si el sistema se entendió. Un equipo que abre el editor de código antes de haber nombrado las piezas suele rehacer el trabajo. Un equipo que nombra, relaciona y luego dibuja llega más limpio al código en otra clase. Este párrafo pide paciencia lectora. No se salten palabras porque “ya se entiende”. Las palabras que parecen obvias —contenedor, grupo, valor, respuesta— son las que luego fallan. Subrayen mentalmente una frase de este bloque que todavía no puedan parafrasear. Esa frase debe aparecer, aclarada, en Canva. La comprensión no es una sensación: es la capacidad de decirlo de otra manera y de señalarlo en un esquema. Si solo pueden repetir el párrafo, aún están en la lectura literal. El siguiente paso es la lectura inferencial: qué se sigue de lo leído. Practíquenla ahora, en voz alta, con una sola inferencia del caso.`,
      `El producto no es el código todavía: es el mapa del caso en Canva, expuesto frente al grupo por todo el equipo. El mapa debe permitir señalar ventana, zonas, decisión, canal y respuesta. Si falta una, el caso no se comprendió. Si sobran diez iconos, el caso se disfrazó. Este cierre convierte la lectura extensa en evidencia pública. Cualquier integrante explica; nadie “se esconde” porque no le tocó dibujar. Antes de proyectar, el equipo ensaya un minuto. Si no les alcanza, el mapa tiene demasiado texto o demasiado poco orden. Recorten. El objetivo de fomentar lectura, análisis y comprensión se cumple cuando el salón oye una explicación clara que nació de los párrafos, no de un tutorial abierto en el celular. Cierren con una frase de una línea que resuma el caso. Esa frase es el centro del organizador. Si no pueden escribirla, vuelvan a los párrafos anteriores y busquen la decisión del usuario: ahí está el núcleo. Luego sí, expongan. El ${n} de ${of} no lee el texto otra vez: enseña el sistema que leyó.`,
    ];
  }
  if (angle === "diseno") {
    return [
      `No todo se resuelve con «${t}». Diseñar también es decir que no. Si el usuario puede marcar varias cosas a la vez, no es exclusión mutua. Si el enunciado pide acumular, otra herramienta conviene. Leer un problema de interfaz es, antes que nada, leer el tipo de decisión. Quien se salta esa lectura llega al control de moda y lo pega donde no va. El programa “se ve profesional” y enseña una regla falsa. Este párrafo pide un hábito: clasificar la decisión antes de dibujar. ¿Es una sola? ¿Son varias? ¿Es un número? ¿Es un texto libre? Cada respuesta empuja a un diseño distinto. «${t}» solo gana en algunos de esos casos. El análisis consiste en defender por qué sí o por qué no, con razones, no con gustos. En el organizador gráfico esa defensa se vuelve una caja de “criterio de uso”. Sin criterio, el mapa es un afiche del tema de la semana. Lean despacio un enunciado escolar inventado por ustedes y clasifíquenlo. Si no pueden clasificarlo, el enunciado está ambiguo: reescríbanlo. Reescribir el problema también es comprenderlo. No pasen a Canva con una ambigüedad en el centro: se va a notar en la exposición.`,
      `Si todo es un solo botón, no hace falta un grupo. Si no hay zonas, el contenedor sobra. El enunciado se lee antes que el código, igual que un texto se comprende antes de resumirlo. Muchos mapas fracasan porque dibujan piezas que el problema no pidió. Eso no es creatividad: es no haber leído. Este párrafo invita a borrar. Borrar es un acto de análisis. Pregunten qué quitarían y qué dejaría de funcionar al quitarlo. Lo que se puede quitar no era esencial; lo que no se puede quitar es la estructura. En ${m} también pasa: hay elementos de adorno y elementos que sostienen el orden. Traduzcan esa idea a «${t}». El organizador debería tener una caja de “esencial” y una de “accesorio”. Si todo les parece esencial, todavía no recortaron. Recortar duele porque da la impresión de “hacer menos”. En comprensión lectora, recortar es señalar la idea principal. Hagan ahora el ejercicio en voz alta: un integrante propone una pieza de más, otro defiende por qué sobra, un tercero decide. Esa conversación es el producto intelectual. Canva solo la va a fotografiar.`,
      `Escriban un ejemplo escolar donde «${t}» SÍ aplica. Tiene que ser una sola decisión clara, situada en un trámite que el grupo reconozca: turno, materia, formato de archivo, tipo de examen, permiso, color de equipo. El ejemplo no puede ser genérico (“una ventana con opciones”) porque lo genérico no se puede analizar. Un ejemplo concreto obliga a nombrar la pregunta, las alternativas y la consecuencia. Si no pueden nombrar las alternativas, el ejemplo está incompleto. Este párrafo es deliberadamente práctico. La lectura se comprende cuando se encarna. Lean su ejemplo como si fuera un problema de examen de comprensión: ¿cuál es la idea principal?, ¿qué detalles son relevantes?, ¿qué se inferiría si faltara «${t}»? Esas tres preguntas de español se aplican aquí sin disfraz. Llévenlas al mapa. Un organizador de “sí aplica” con pregunta, alternativas y consecuencia ya enseña. Si el equipo no alcanza a llenar las tres, el ejemplo era un título, no un caso. Vuelvan a escribirlo. La reescritura es parte de la lectura, no un retraso.`,
      `Escriban otro ejemplo donde sería un error usarlo. Ahí proponen con qué lo sustituirían y por qué. Este “no” es tan importante como el “sí”. Quien solo sabe aplicar un tema en el caso obvio aún no comprende el límite. El límite es el análisis. Busquen un enunciado que parezca del tema y no lo sea: varias marcas a la vez, un dato libre, una acción única sin elección, una lista que no decide nada. Expliquen la trampa. En el organizador, el ejemplo del no no puede ser una caja triste al margen: es simétrico al sí. Dos columnas. Dos justificaciones. Si el “no” se resuelve con “porque no”, no hubo comprensión. Tiene que haber un porque que un oyente pueda repetir. Relaciónenlo con «${t}» y no con un prejuicio (“eso está más difícil”). La sesión busca que el salón oiga criterios. Un criterio se puede enseñar; un gusto no. Practiquen decir el criterio en una oración. Esa oración irá al centro de la lámina o justo debajo del título. Si no cabe en una oración, todavía está enredada: sigan leyendo y recortando.`,
      `Esta mirada es de la sesión ${week}. Aunque el tema se repita la próxima semana, el par de ejemplos tiene que ser otro. Repetir el tema no autoriza a repetir la lectura. Comprender de verdad es poder generar ejemplos nuevos. Si el equipo solo recicla el de la columna vecina o el de la clase pasada, está en la memoria de corto plazo, no en la comprensión. Pónganle nombre propio a sus dos ejemplos. El nombre obliga a la concreción. Luego, en la exposición, no lean los párrafos: cuenten los dos ejemplos y el criterio que los separa. Cualquier integrante debe poder contar ambos. Si solo el que “se expresa mejor” puede, el equipo no leyó junto. Vuelvan a los textos y hagan una ronda: cada quien dice una pieza del sí o del no. Así se fomenta la lectura compartida. El ${n} de ${of} se va a distinguir, o no, por la calidad de esos ejemplos, no por lo recargado del Canva. Un mapa claro con dos casos bien pensados gana a una lámina llena de clipart.`,
      `Esos dos ejemplos —sí / no— son el corazón del organizador. Pásenlos a Canva y explíquenlos en la exposición. Añadan una flecha de criterio y una pregunta de comprensión que el salón pueda responder al escucharlos. Si nadie en el grupo puede responder esa pregunta, el mapa no enseñó. Este cierre no pide más dibujo: pide evidencia. Evidencia de que leyeron, de que analizaron límites y de que comprendieron cuándo «${t}» sí y cuándo no. Antes de proyectar, borren todo lo que no sirva para contar esos dos casos. Lo que quede debe poder señalarse con el dedo. Si necesitan un párrafo entero para explicar una caja, la caja está mal nombrada: cámbienle el título. Nombrar bien es comprender. El producto es de todo el equipo. El análisis también. No hay rol de “el que piensa” y “el que decora”. Quien leyó su párrafo largo tiene algo que aportar al sí o al no. Si alguien no sabe dónde encaja lo que leyó, el equipo vuelve al texto, no improvisen. La lectura es la fuente. Canva es el espejo.`,
    ];
  }
  if (angle === "relacion") {
    return [
      `«${t}» no llega de la nada. Se apoya en cosas que ya vieron: una ventana, un evento de clic, una variable, un acomodo, un contenedor. Leer un tema nuevo es, en buena medida, leer sus deudas. Quien trata cada clase como isla vuelve a empezar siempre y no comprende. Quien busca puentes, avanza. Este párrafo pide que el equipo haga memoria lectora: ¿qué idea anterior es imposible quitar si queremos usar «${t}»? Si no pueden nombrarla, el tema nuevo está flotando. El análisis consiste en distinguir apoyo de adorno. No todo lo visto antes es necesario aquí. Elegir el apoyo correcto es comprender la red de conceptos. En el organizador, ese apoyo no es una caja lejana: es una flecha que entra al centro. Una flecha sin origen claro es un adorno. Digan el origen en voz alta. Si tardan demasiado, no es porque “no se acuerden”: es porque aún no relacionaron. Vuelvan a leer y busquen en este bloque las pistas. Están escritas para ser halladas, no para ser adivinadas. La comprensión se siente cuando la idea anterior y la nueva se pueden decir en una sola oración con un porque.`,
      `Si el contenedor es la caja, la opción exclusiva es la pregunta y la variable es el canal, entonces mezclar idiomas de acomodo rompe la relación. Las piezas no viven solas: se sostienen. Leer relaciones es más difícil que leer definiciones, porque hay que mantener varias ideas a la vez. Por eso este párrafo es extenso. Pide que el equipo no se quede en “esto es X”. Pide “esto es X porque Y lo necesita”. Esa fórmula —es, porque, necesita— es análisis. Practíquenla tres veces, con tres parejas de conceptos ligados a «${t}». Si no alcanzan tres, aún están en la superficie. El mapa cognitivo de relaciones no es un sol con rayitos: es una red con direcciones. Una red se explica recorriéndola, no señalando el centro. En la exposición, el recorrido es el texto. Si improvisan el orden, el salón no comprende aunque el dibujo sea bonito. Numeren las flechas. El número obliga a haber leído un orden posible. Relaciónenlo, si hace falta, con ${m}: un sistema con zonas que dependen unas de otras. Lo que no depende, sobra. Lo que depende y no está dibujado, faltó.`,
      `Dibujen una flecha de lo viejo a lo nuevo. ¿Qué idea de clases anteriores es imposible quitar? Justifíquenla con un “si quito esto, entonces…”. El entonces es la prueba de comprensión. Sin entonces, la flecha es un capricho. Este párrafo pide un ejercicio de lectura inferencial. No está escrito el nombre exacto de “la idea vieja” porque el equipo tiene que recuperarla. Recuperar información y relacionarla es exactamente lo que se evalúa cuando se habla de comprensión lectora. Háganlo en voz alta. Si hay dos candidatas, mejor: discutan cuál es más necesaria para «${t}». El desacuerdo, resuelto con razones, es análisis. En Canva, esa flecha debe tener etiqueta, no solo color. Un color sin texto no enseña. Un texto de tres palabras suele ser débil; una etiqueta de una oración, más honesta. No teman el texto en el mapa si el texto es preciso. Teman el texto de relleno. Este equipo, el ${n} de ${of}, se va a distinguir por la calidad de esa primera flecha. No la dejen genérica (“lo de la clase pasada”). Nombren.`,
      `Una segunda flecha: cómo el evento necesita a la variable, o cómo la acción necesita haber leído un valor. Sin esa pareja, el clic no significa nada. Muchos estudiantes dibujan un botón y se detienen, porque el botón se ve. La relación invisible es la que hay que leer. Este párrafo insiste en lo invisible. Un organizador que solo muestra lo visible es un dibujo de la pantalla, no un mapa del sistema. El sistema incluye lo que el usuario no ve. Comprender «${t}» es poder hablar de esa parte sin sonrojarse por “no salir en la ventana”. En la exposición, señalen lo invisible a propósito. Digan: “esto no se ve, pero si falta, esto otro se rompe”. Esa frase demuestra análisis. Si no pueden completarla, vuelvan a este párrafo y extraigan la pareja. Está dicha más de una vez para que no se escape. Relaciónenla con un gesto del salón: levantar la mano no sirve si nadie anota quién fue. El gesto es el evento; la anotación es el canal. Traduzcan. Traducir es comprender.`,
      `Una tercera flecha: cómo el usuario entiende la pantalla. Si el grupo no se ve como grupo, la lectura del diseño falló aunque el código interno sea “correcto”. Hay dos lecturas, entonces: la del programador y la del usuario. Un equipo que solo mira el código no ha terminado de leer. Un equipo que solo mira lo bonito tampoco. Este párrafo pide la doble lectura. En el organizador, pueden ser dos orillas: “se entiende por dentro” y “se entiende por fuera”. Las flechas cruzan. Si no cruzan, el tema quedó partido. Inventen un contraejemplo: un diseño interno correcto que el usuario malinterpreta. Ese contraejemplo es oro para la exposición. No tiene que ser real; tiene que ser plausible y ligado a «${t}». La sesión ${week} pide esa profundidad. No se conformen con definir. Relacionen. Si al terminar las tres flechas el mapa parece un laberinto, recorten etiquetas, no relaciones. Las relaciones son el contenido. Las etiquetas se pueden acortar cuando ya se comprendieron.`,
      `Tres flechas son un mapa. Háganlo en Canva, una sola lámina del equipo, y preséntenla al salón. El criterio de éxito no es que “se vea llena”. Es que un compañero de otra columna pueda recorrer las tres flechas y repetir el porque de cada una. Si no puede, no hubo enseñanza. Este cierre convierte la lectura en producto compartido. Ensayen el recorrido. Cualquier integrante empieza; otro continúa; un tercero cierra. Así se nota que todos leyeron, no que uno entendió y los demás firmaron. Si alguien no puede continuar, el equipo vuelve a su párrafo, no lo cubran. Cubrir a alguien es impedir la comprensión. El objetivo de fomentar lectura se cumple cuando el texto largo se vuelve un esquema hablable. «${t}» debe quedar en el centro, las ideas previas a un lado, lo invisible al otro, el usuario abajo o arriba: elijan una geometría y defiéndanla. Defender la geometría del mapa también es análisis. No copien una plantilla de Canva que no corresponde. La plantilla no leyó con ustedes.`,
    ];
  }
  return [
    `Cierren con un plan, no con un copiar-pegar. «${t}» se vuelve pasos: qué se crea primero, qué se conecta después y qué se prueba al final. Un plan es un texto de comprensión. Si no se puede dictar, no se comprendió. Este párrafo pide que el equipo deje de pensar en “la práctica” como abrir el editor. La práctica de esta sesión es escribir un plan breve, nacido de la lectura, y plasmarlo en un organizador. Quien abre tutoriales en otra pestaña está evadiendo el análisis. El plan tiene dueño: este equipo, sesión ${week}. No puede ser el plan de la columna vecina. Empiecen por nombrar el propósito en una oración. Si el propósito es “hacer una ventana”, es débil. Si el propósito nombra la decisión del usuario y el papel de «${t}», ya hay lectura. Anoten esa oración. Es el título del mapa. Luego resistan la tentación de llenar diez cajas. Tres zonas y una prueba suelen bastar. Recortar el plan es comprender la idea principal. Ampliarlo sin criterio es miedo a que “se vea poco”. En comprensión lectora, lo poco bien dicho gana.`,
    `Anoten el nombre de la ventana y cuántas zonas necesita. Si hay más de tres, recorten. Nombrar la ventana no es un detalle tonto: obliga a decir de qué va el programa. Las zonas obligan a decir quién contiene a quién. Un plan sin zonas es una lista de controles huérfanos. Este párrafo pide arquitectura mínima. Relaciónenla con ${m}: un conjunto con pocos compartimentos, cada uno con una función. Si una zona no tiene función, sobra. Si una función no tiene zona, el plan está incompleto. Hagan el cruce en voz alta. Esa tabla función/zona es material directo de Canva. No la dejen en el aire. Un organizador puede ser, sencillamente, esa tabla convertida en cajas. No subestimen lo simple si es verdadero. Lo recargado suele esconder que no se comprendió qué era esencial. Lean otra vez y busquen una zona que puedan fusionar. Fusionar con razón es análisis. Fusionar por flojera, no. La razón debe poder decirse: “estas dos cosas las lee el usuario como una sola pregunta”. Si no hay razón, no fusionen.`,
    `Anoten la pregunta que hace el grupo de opciones —o la decisión que modela «${t}»— y cómo se llama el canal que guarda la respuesta. Sin nombre, no hay lectura del resultado: hay un ademán en la pantalla. Ponerle nombre es un acto de comprensión. Los nombres vagos (dato, cosa, var1) delatan que el equipo no leyó el problema. Un nombre preciso enseña. Este párrafo pide que elijan el nombre como si fuera a leerlo alguien de otro equipo. Si ese alguien no entiende el nombre, cámbienlo. En el mapa, el canal no es un globito: es el puente entre la elección y la respuesta. Dibujen el puente. Si no hay puente, el plan se cae al llegar al botón. Practiquen decir: “el usuario elige, esto se guarda en X, luego Y lee X”. Esa frase es el corazón del plan. Si no sale fluida, vuelvan a este bloque. No adelanten Canva con una frase entrecortada: se va a notar frente al grupo. La lectura extensa sirve para que esa frase se acomode. Aprovechen el tiempo. No lo gasten buscando plantillas.`,
    `Anoten qué hace la acción final. Una acción. Si el plan no se puede decir en un minuto, está demasiado grande. La acción es el lugar donde se demuestra si se comprendió el flujo. Un mensaje que no depende de la elección es teatro. Un mensaje que sí depende, aunque sea corto, es un programa. Este párrafo pide modestia inteligente. No prometan diez funciones. Prometan una lectura fiel de «${t}». En el organizador, la acción es una caja con entrada (el valor) y salida (lo que se muestra). Si la caja no tiene entrada, es un adorno. Analicen un “qué pasaría si el usuario no elige”. Ese caso borde también es comprensión. Muchos planes lo olvidan y el programa nace mudo. Inclúyanlo. No tiene que ser código: tiene que ser una decisión de diseño dicha en español claro. El salón debería poder oírla y repetirla. Si no, reescríbanla. Reescribir el plan es releer el tema. Ese ciclo —leer, decir, corregir— es exactamente lo que se busca fomentar.`,
    `Comparen el plan con ${m}: si alguna zona sobra, quítenla. Esta es la sesión ${week}; el plan no puede ser el de la semana pasada ni el de otro color. La analogía sirve aquí como navaja: lo que no tiene equivalente útil, se va. No fuerce la analogía para que “todo calce”. Reconocer lo que no calza también es análisis. El ${n} de ${of} defiende su recorte. En la exposición, digan qué quitaron y por qué. Esa frase suele convencer más que una lámina llena. Un organizador honesto muestra el recorte. Pueden poner, incluso, una caja pequeña de “esto no entra y por qué”. Es una caja de comprensión lectora: idea principal versus secundaria. Hagan ahora esa distinción en voz alta. Si todo les parece principal, todavía no leyeron con jerarquía. Vuelvan a los párrafos y marquen una sola idea que, si se cae, derrumba el plan. Esa es la principal. El resto se ordena alrededor. Canva debe reflejar esa jerarquía: centro grande, detalles menores. Si todo tiene el mismo tamaño, el mapa no pensó.`,
    `Pasen el plan a un organizador en Canva. Todo el equipo expone esa única lámina. Nadie lee el texto de otro color y nadie lee su párrafo otra vez como si fuera la exposición. La exposición recorre el plan: propósito, zonas, canal, acción, recorte. Cinco estaciones. Si una estación no se puede señalar, falto análisis. Este cierre es el contrato de la sesión: se leyó un texto largo, se analizó, se comprendió y se plasmó. El producto es de todos. Cualquier integrante continúa si otro se traba. Si se traban dos, el equipo no está listo: vuelvan al texto, no improvisen para “salir del paso”. Fomentar lectura es también tolerar esa segunda pasada. No es perder el tiempo. Es exigir sentido. Cuando proyecten, el salón debería poder copiar en un cuaderno el esquema, no el párrafo. Ese es el indicador. «${t}» queda entendido no cuando se oyó, sino cuando se pudo organizar. Organicen. Luego sí, expliquen. El mapa es el examen visible de la comprensión.`,
  ];
}

export function generateBloque(params: {
  topic: string;
  teamIndex: number;
  teamCount: number;
  sessionNumber: number;
  teamLabel: string;
  memberCount: number;
}): GeneratedBloque {
  const topic = cleanTopic(params.topic) || "el tema de la clase";
  const seed = hashSeed(`${topic}|${params.sessionNumber}|${params.teamIndex}|${params.teamLabel}`);
  const angle = ANGLES[(params.sessionNumber + params.teamIndex) % ANGLES.length]!;
  const metaphor = pick(METAPHORS, seed, 1);
  const n = params.teamIndex + 1;
  const of = params.teamCount;
  const week = params.sessionNumber;
  const claveBase = topic
    .split(/[,\-/]| y /i)
    .map((p) => p.trim())
    .filter(Boolean)
    .slice(0, 3);
  while (claveBase.length < 3) claveBase.push(["concepto", "uso", "error"][claveBase.length]!);

  const raw = sixParagraphs(topic, metaphor, week, n, of, angle);
  const parrafos = assignParagraphs(raw, Math.max(1, params.memberCount));
  const texto = parrafos.join("\n\n");

  const titles: Record<(typeof ANGLES)[number], string> = {
    que_es: `Qué es «${topic}»`,
    analogia: `Como ${metaphor}: ${topic}`,
    como_se_usa: `Cómo se usa «${topic}»`,
    errores: `Errores al aplicar «${topic}»`,
    caso: `Un caso con «${topic}»`,
    diseno: `¿Cuándo sí y cuándo no? «${topic}»`,
    relacion: `Cómo se conecta «${topic}»`,
    cierre_practica: `Plan mínimo de «${topic}»`,
  };

  return {
    titulo: titles[angle],
    mision:
      "Cada integrante lee EN VOZ ALTA su párrafo (lectura extensa). Escuchen, analicen y comprendan. Luego el equipo entero plasma esas ideas en un solo organizador en Canva y lo expone.",
    texto,
    parrafos,
    clave: [...claveBase, angle.replace("_", " ")],
    preguntaGuia: `Después de leer los ${parrafos.length} párrafos, ¿cuál es la idea central de «${topic}», qué relaciones vieron y qué no puede faltar en el organizador gráfico?`,
    producto: productCopy(topic),
    organizador: [
      { caja: "Idea central", hijos: topic },
      { caja: "De cada párrafo", hijos: "Una idea, una relación o un ejemplo (no una frase copiada)" },
      { caja: "Análisis", hijos: "Qué es / qué no es / qué pasa si falta" },
      { caja: "Producto", hijos: "Una lámina en Canva · todo el equipo expone" },
    ],
  };
}
