export type IcebreakerEnergy = "baja" | "media" | "alta";
export type IcebreakerFormation =
  | "circulo"
  | "parejas"
  | "trios"
  | "equipos"
  | "filas"
  | "mezcla"
  | "spotlight"
  | "libre";

export type IcebreakerStep = {
  title: string;
  detail: string;
};

export type IcebreakerActivity = {
  id: string;
  title: string;
  tagline: string;
  minutes: number;
  energy: IcebreakerEnergy;
  formation: IcebreakerFormation;
  /** Cuántas personas se sortean al girar (0 = no sortea alumnos). */
  spotlightCount: number;
  /** Si true, muestra diagrama de formación + pasos ilustrados. */
  illustrated: boolean;
  materials: string;
  setupFor32: string;
  steps: IcebreakerStep[];
  tip: string;
};

export const ICEBREAKER_ACTIVITIES: IcebreakerActivity[] = [
  {
    id: "nombre-gesto",
    title: "Nombre + gesto",
    tagline: "Presentación rápida en círculo",
    minutes: 8,
    energy: "media",
    formation: "circulo",
    spotlightCount: 1,
    illustrated: true,
    materials: "Ninguno",
    setupFor32: "Círculo amplio (pasillo o patio). Quien empieza lo marca la ruleta.",
    steps: [
      { title: "Formar círculo", detail: "Todos de pie, dejando espacio para mover brazos." },
      { title: "Turno", detail: "Cada persona dice su nombre y hace un gesto único." },
      { title: "Eco", detail: "El grupo repite a coro: nombre + gesto." },
      { title: "Cadena", detail: "Siguiente persona a la derecha continua hasta cerrar el círculo." },
    ],
    tip: "Si el tiempo apremia, haz dos semicírculos de 16 en paralelo.",
  },
  {
    id: "dos-verdades",
    title: "2 verdades y 1 mentira",
    tagline: "Adivinar en parejas",
    minutes: 7,
    energy: "baja",
    formation: "parejas",
    spotlightCount: 0,
    illustrated: true,
    materials: "Ninguno",
    setupFor32: "16 parejas. Si hay impar, forma un trío.",
    steps: [
      { title: "Emparejar", detail: "Cuenta 1-2 / 1-2 por la fila o deja que se junten con quien no hablan." },
      { title: "Inventar", detail: "Cada uno prepara 2 hechos reales y 1 inventado (30 s)." },
      { title: "Adivinar", detail: "Comparten y el compañero marca cuál cree que es la mentira." },
      { title: "Revelar", detail: "Revelan la mentira y rotan pareja una vez si hay tiempo." },
    ],
    tip: "Pide temas seguros: hobbies, comida, viajes, series.",
  },
  {
    id: "mapa-humano",
    title: "Mapa humano",
    tagline: "Ubicarse según criterios",
    minutes: 6,
    energy: "media",
    formation: "mezcla",
    spotlightCount: 0,
    illustrated: true,
    materials: "Espacio libre en el salón",
    setupFor32: "Define paredes como norte/sur/este/oeste o extremos de un eje.",
    steps: [
      { title: "Eje 1", detail: "“Muévanse según dónde nacieron” (cerca/lejos del campus)." },
      { title: "Eje 2", detail: "“Prefieren mañana o noche” — dos lados del salón." },
      { title: "Microcharla", detail: "30 s con la persona más cercana: ¿por qué están ahí?" },
      { title: "Cierre", detail: "Una persona de cada extremo comparte 1 dato curioso." },
    ],
    tip: "Cambia el criterio 3 veces para que se mezclen.",
  },
  {
    id: "balon-preguntas",
    title: "Pelota de preguntas",
    tagline: "Pase + pregunta rápida",
    minutes: 8,
    energy: "alta",
    formation: "circulo",
    spotlightCount: 1,
    illustrated: true,
    materials: "Pelota suave, borrador o peluche",
    setupFor32: "Círculo o dos círculos de 16. Quien inicia lo elige la ruleta.",
    steps: [
      { title: "Regla", detail: "Quien atrapa responde una pregunta corta y lanza a alguien nuevo." },
      { title: "Banco", detail: "Docente lanza preguntas: hobby, canción, meta del semestre…" },
      { title: "No repetir", detail: "No se lanza a quien ya respondió hasta que todos participen." },
      { title: "Cierre", detail: "Último pase: “algo que espero de esta clase”." },
    ],
    tip: "Con 32, divide en 2 círculos para no perder ritmo.",
  },
  {
    id: "bingo-humano",
    title: "Bingo humano",
    tagline: "Encontrar compañeros que…",
    minutes: 10,
    energy: "alta",
    formation: "mezcla",
    spotlightCount: 0,
    illustrated: true,
    materials: "Hoja bingo (o pizarra con 9 casillas) y pluma",
    setupFor32: "Todos circulan. Cada casilla = 1 firma de compañero distinto.",
    steps: [
      { title: "Mostrar casillas", detail: "Ej: toca instrumento, tiene mascota, vio la misma serie…" },
      { title: "Buscar", detail: "Preguntan y firman. No pueden repetir persona en su hoja." },
      { title: "Bingo", detail: "Primero en llenar 3 en línea grita “¡Bingo!” y verifica." },
      { title: "Compartir", detail: "Lee 2 casillas curiosas en voz alta." },
    ],
    tip: "Puedes proyectar las 9 casillas y que anoten en el cuaderno.",
  },
  {
    id: "espejo-pares",
    title: "Espejo en movimiento",
    tagline: "Sincronía sin hablar",
    minutes: 5,
    energy: "media",
    formation: "parejas",
    spotlightCount: 0,
    illustrated: true,
    materials: "Ninguno (música suave opcional)",
    setupFor32: "16 parejas frente a frente, 1 m de distancia.",
    steps: [
      { title: "Líder A", detail: "A mueve lento; B copia como espejo (45 s)." },
      { title: "Cambio", detail: "Cambian roles (45 s)." },
      { title: "Libre", detail: "Sin líder: intentan moverse juntos (30 s)." },
      { title: "Reflexión", detail: "Una frase: ¿fue fácil sincronizar?" },
    ],
    tip: "Ideal antes de trabajo en equipo o butacas nuevas.",
  },
  {
    id: "entrevista-relampago",
    title: "Entrevista relámpago",
    tagline: "Presentar al compañero",
    minutes: 9,
    energy: "media",
    formation: "parejas",
    spotlightCount: 2,
    illustrated: true,
    materials: "Ninguno",
    setupFor32: "Parejas. Al final, 2 personas sorteadas presentan a su pareja ante el grupo.",
    steps: [
      { title: "Preguntas", detail: "Nombre, algo que se les da bien, meta del mes (90 s c/u)." },
      { title: "Notas", detail: "Escuchan con atención; no escriben si no quieren." },
      { title: "Spotlight", detail: "Las 2 personas sorteadas presentan a su pareja en 20 s." },
      { title: "Aplauso", detail: "Aplauso grupal y se sientan." },
    ],
    tip: "Rota parejas si ya se conocen mucho.",
  },
  {
    id: "estadisticas-vivas",
    title: "Estadísticas vivas",
    tagline: "Votar con el cuerpo",
    minutes: 6,
    energy: "media",
    formation: "filas",
    spotlightCount: 0,
    illustrated: true,
    materials: "Ninguno",
    setupFor32: "Define 4 rincones: Totalmente de acuerdo / De acuerdo / En desacuerdo / Nada.",
    steps: [
      { title: "Afirmación", detail: "Docente dice una frase (ej. “prefiero proyectos en equipo”)." },
      { title: "Moverse", detail: "Cada quien camina al rincón que elige." },
      { title: "Microvoz", detail: "Un voluntario por rincón explica en 10 s." },
      { title: "Repetir", detail: "3–4 afirmaciones distintas." },
    ],
    tip: "Mezcla afirmaciones serias y divertidas.",
  },
  {
    id: "cadena-historia",
    title: "Historia colectiva",
    tagline: "Una frase cada quien",
    minutes: 7,
    energy: "baja",
    formation: "circulo",
    spotlightCount: 1,
    illustrated: false,
    materials: "Ninguno",
    setupFor32: "Puede hacerse sentados. Quien inicia lo marca la ruleta.",
    steps: [
      { title: "Inicio", detail: "La persona sorteada empieza: “Había una vez un proyecto…”" },
      { title: "Cadena", detail: "Siguiente suma UNA frase coherente." },
      { title: "Ritmo", detail: "Máximo 8 s por turno; si se atasca, el grupo ayuda." },
      { title: "Final", detail: "Última persona cierra con moral o giro absurdo." },
    ],
    tip: "Con 32, haz 2 historias en paralelo (16 y 16).",
  },
  {
    id: "rock-paper-tour",
    title: "Campeonato PPT",
    tagline: "Piedra-papel-tijera en cascada",
    minutes: 6,
    energy: "alta",
    formation: "mezcla",
    spotlightCount: 1,
    illustrated: true,
    materials: "Ninguno",
    setupFor32: "Todos empiezan. Perdedores se unen a aplaudir al ganador local.",
    steps: [
      { title: "Ronda 1", detail: "Parejas juegan al mejor de 1." },
      { title: "Seguir", detail: "Ganador busca a otro ganador; perdedor lo anima." },
      { title: "Final", detail: "Quedan 2; el grupo corea el duelo." },
      { title: "Campeón", detail: "Aplauso al campeón (o al que marque la ruleta si empate eterno)." },
    ],
    tip: "Muy bueno para despertar un grupo dormido.",
  },
  {
    id: "objetos-imaginarios",
    title: "Objeto invisible",
    tagline: "Mímica en equipo",
    minutes: 8,
    energy: "media",
    formation: "equipos",
    spotlightCount: 0,
    illustrated: true,
    materials: "Lista de objetos en pizarra",
    setupFor32: "8 equipos de 4. Cada equipo en un rincón.",
    steps: [
      { title: "Reparto", detail: "Un representante ve un objeto (sin decirlo)." },
      { title: "Mímica", detail: "Lo actúa; el equipo adivina en 40 s." },
      { title: "Rotar", detail: "Cambia el actor; 3 rondas." },
      { title: "Puntos", detail: "Acierta = 1 punto. Celebran al equipo con más." },
    ],
    tip: "Objetos de la carrera o del salón funcionan mejor.",
  },
  {
    id: "lineup-rapido",
    title: "Fila silenciosa",
    tagline: "Ordenarse sin hablar",
    minutes: 5,
    energy: "media",
    formation: "filas",
    spotlightCount: 0,
    illustrated: true,
    materials: "Ninguno",
    setupFor32: "Una o dos filas largas frente al pizarrón.",
    steps: [
      { title: "Reto", detail: "“Ordérense por fecha de cumpleaños… ¡sin hablar!”" },
      { title: "Gestos", detail: "Solo señas y mímica." },
      { title: "Check", detail: "De un extremo al otro dicen mes/día en voz alta." },
      { title: "Otro criterio", detail: "Repite: altura, distancia a casa, o número de lista." },
    ],
    tip: "Dos filas de 16 aceleran y evitan embotellamiento.",
  },
  {
    id: "tres-cosas-comunes",
    title: "3 cosas en común",
    tagline: "Conexión en tríos",
    minutes: 7,
    energy: "baja",
    formation: "trios",
    spotlightCount: 0,
    illustrated: true,
    materials: "Ninguno",
    setupFor32: "10 tríos + 1 cuarteto (o 8 cuartetos de 4).",
    steps: [
      { title: "Formar", detail: "Agrupa de 3 personas que no suelen juntarse." },
      { title: "Buscar", detail: "Encuentran 3 cosas en común que NO sean obvias (carrera/edad)." },
      { title: "Anunciar", detail: "Un portavoz dice las 3 en 15 s." },
      { title: "Voto", detail: "El grupo vota la conexión más creativa (aplauso)." },
    ],
    tip: "Prohíbe “somos estudiantes” y “vivimos en México”.",
  },
  {
    id: "telefono-descompuesto",
    title: "Teléfono descompuesto",
    tagline: "Mensaje que se deforma",
    minutes: 6,
    energy: "media",
    formation: "filas",
    spotlightCount: 1,
    illustrated: false,
    materials: "Frase secreta escrita",
    setupFor32: "2 filas de 16. La ruleta elige quién inicia cada fila.",
    steps: [
      { title: "Susurro", detail: "El primero recibe la frase al oído." },
      { title: "Cadena", detail: "Pasa el mensaje en susurro hasta el final." },
      { title: "Revelar", detail: "El último dice en voz alta lo que entendió." },
      { title: "Comparar", detail: "Se lee la frase original; risas y aprendizaje." },
    ],
    tip: "Usa frases técnicas del tema del día para conectar con la clase.",
  },
  {
    id: "energia-clap",
    title: "Clap sync",
    tagline: "Ritmo grupal",
    minutes: 4,
    energy: "alta",
    formation: "circulo",
    spotlightCount: 1,
    illustrated: false,
    materials: "Ninguno",
    setupFor32: "De pie. Quien lleva el ritmo lo marca la ruleta.",
    steps: [
      { title: "Pulso", detail: "Líder marca palmadas lentas; todos siguen." },
      { title: "Acelerar", detail: "Sube velocidad hasta casi imposible." },
      { title: "Congelar", detail: "Al grito “¡ya!” todos congelan en pose." },
      { title: "Reset", detail: "Respiran 5 s y se sientan listos." },
    ],
    tip: "Perfecto como reset de 2 minutos entre bloques.",
  },
  {
    id: "superpoder-falso",
    title: "Superpoder inventado",
    tagline: "Presentación creativa",
    minutes: 8,
    energy: "media",
    formation: "circulo",
    spotlightCount: 4,
    illustrated: false,
    materials: "Ninguno",
    setupFor32: "Todos piensan uno; solo 4 sorteados lo cuentan al frente.",
    steps: [
      { title: "Inventar", detail: "En silencio: nombre del poder + para qué lo usarían (40 s)." },
      { title: "Spotlight", detail: "Las 4 personas sorteadas pasan al frente (20 s c/u)." },
      { title: "Voto rápido", detail: "Aplauso al poder más útil para el semestre." },
      { title: "Cierre", detail: "El resto comparte su poder con el de al lado." },
    ],
    tip: "Anima poderes absurdos: “pausar WiFi ajeno”, “duplicar USB”…",
  },
  {
    id: "cambio-de-lugar",
    title: "Cambio de lugar",
    tagline: "Levántense si…",
    minutes: 6,
    energy: "alta",
    formation: "circulo",
    spotlightCount: 1,
    illustrated: true,
    materials: "Sillas en círculo (n-1) o marcas en el piso",
    setupFor32: "31 sillas + 1 persona al centro (la ruleta elige al centro).",
    steps: [
      { title: "Centro", detail: "Quien está al centro dice: “Cambien de lugar quienes…”" },
      { title: "Corrida", detail: "Los que aplican se levantan y buscan otra silla." },
      { title: "Nuevo centro", detail: "Quien se queda sin silla pasa al centro." },
      { title: "Rondas", detail: "5–7 rondas; última: “quienes quieren un buen semestre”." },
    ],
    tip: "Sin sillas: usan mochilas como “base” en el piso.",
  },
  {
    id: "dibujo-ciego",
    title: "Dibujo a ciegas",
    tagline: "Instrucciones precisas",
    minutes: 8,
    energy: "baja",
    formation: "parejas",
    spotlightCount: 0,
    illustrated: true,
    materials: "Hojas y plumas",
    setupFor32: "16 parejas espalda con espalda o uno mirando pizarra.",
    steps: [
      { title: "Roles", detail: "A ve una figura simple; B no la ve." },
      { title: "Dictar", detail: "A describe solo con palabras; B dibuja (90 s)." },
      { title: "Comparar", detail: "Muestran original vs dibujo." },
      { title: "Cambio", detail: "Intercambian roles con otra figura." },
    ],
    tip: "Figuras: casa, estrella, logo simple, diagrama del tema.",
  },
  {
    id: "debate-relampago",
    title: "Debate 60 segundos",
    tagline: "Argumentar en equipos",
    minutes: 9,
    energy: "media",
    formation: "equipos",
    spotlightCount: 2,
    illustrated: true,
    materials: "Tema polémico ligero en pizarra",
    setupFor32: "2 equipos de 16 (A favor / En contra). Ruleta elige 1 voz por bando.",
    steps: [
      { title: "Tema", detail: "Ej: “¿Clases 100% con celular permitido?”" },
      { title: "Prep", detail: "2 min en equipo: 3 argumentos." },
      { title: "Duelo", detail: "Portavoces sorteados hablan 60 s c/u." },
      { title: "Réplica", detail: "30 s de réplica y aplauso; no hay “ganador” oficial." },
    ],
    tip: "Temas divertidos evitan tensión real.",
  },
  {
    id: "emoji-dia",
    title: "Clima del día",
    tagline: "Check-in emocional rápido",
    minutes: 4,
    energy: "baja",
    formation: "libre",
    spotlightCount: 0,
    illustrated: false,
    materials: "Ninguno (o pizarra con 4 caritas)",
    setupFor32: "De pie en su lugar o en butaca.",
    steps: [
      { title: "Escala", detail: "Muestran con dedos 1–5 cómo llegan hoy." },
      { title: "Vecino", detail: "15 s: dicen a su vecino UNA palabra del día." },
      { title: "Docente", detail: "Agradece la honestidad; no fuerza detalles." },
      { title: "Arranque", detail: "Pasan al contenido de la clase." },
    ],
    tip: "Útil los lunes o después de un examen.",
  },
  {
    id: "mision-secreta",
    title: "Misión secreta",
    tagline: "Ayudar sin que se note",
    minutes: 10,
    energy: "media",
    formation: "mezcla",
    spotlightCount: 0,
    illustrated: false,
    materials: "Papelitos con misiones",
    setupFor32: "Cada alumno saca un papelito al entrar.",
    steps: [
      { title: "Misiones", detail: "Ej: “haz reír a alguien”, “ayuda a guardar sillas”, “saluda a 3”." },
      { title: "Actuar", detail: "Durante 5 min de mingling cumplen la misión en secreto." },
      { title: "Revelar", detail: "Voluntarios cuentan si creen haberlo logrado." },
      { title: "Puente", detail: "Conecta con colaboración del proyecto del día." },
    ],
    tip: "Prepara 32 papelitos (puedes repetir misiones).",
  },
  {
    id: "carrera-de-asientos",
    title: "Busca tu gemelo",
    tagline: "Encontrar pareja por criterio",
    minutes: 5,
    energy: "alta",
    formation: "mezcla",
    spotlightCount: 0,
    illustrated: true,
    materials: "Ninguno",
    setupFor32: "Espacio para caminar entre butacas.",
    steps: [
      { title: "Criterio", detail: "“Busquen a alguien con el mismo mes de cumpleaños”." },
      { title: "Confirmación", detail: "Al encontrarlo chocan manos y se quedan juntos." },
      { title: "Sobrantes", detail: "Quienes no hallan forman un “club de únicos”." },
      { title: "Otro round", detail: "Nuevo criterio: color favorito, deporte, serie…" },
    ],
    tip: "2–3 rondas bastan; luego sientan en esas parejas.",
  },
  {
    id: "yes-and",
    title: "Sí, y…",
    tagline: "Improvisación positiva",
    minutes: 6,
    energy: "media",
    formation: "parejas",
    spotlightCount: 0,
    illustrated: false,
    materials: "Ninguno",
    setupFor32: "16 parejas. Tema: planear un viaje absurdo o un invento.",
    steps: [
      { title: "Regla", detail: "Nunca digan “no”; respondan “Sí, y…” + aportan idea." },
      { title: "Ronda", detail: "2 minutos improvisando el plan juntos." },
      { title: "Titular", detail: "Inventan un título de 5 palabras para su plan." },
      { title: "Galería", detail: "3 parejas voluntarias leen su título." },
    ],
    tip: "Excelente antes de brainstorming de proyectos.",
  },
  {
    id: "contadores-humanos",
    title: "Contadores humanos",
    tagline: "Contar en equipo sin planear",
    minutes: 5,
    energy: "media",
    formation: "circulo",
    spotlightCount: 0,
    illustrated: false,
    materials: "Ninguno",
    setupFor32: "Todos de pie. Meta: contar de 1 a 20 (o 32) sin repetir ni hablar a la vez.",
    steps: [
      { title: "Regla", detail: "Una voz a la vez; si chocan dos, reinician en 1." },
      { title: "Intento", detail: "Varios intentos; celebran cada récord." },
      { title: "Estrategia", detail: "Tras 2 fallos, 20 s para acordar señas (sin asignar números)." },
      { title: "Logro", detail: "Al llegar a la meta, aplauso fuerte." },
    ],
    tip: "Con 32, meta a 15 es más realista al inicio.",
  },
  {
    id: "galeria-talentos",
    title: "Mini talento 15 s",
    tagline: "Showcase express",
    minutes: 8,
    energy: "alta",
    formation: "spotlight",
    spotlightCount: 5,
    illustrated: true,
    materials: "Ninguno (o parlante)",
    setupFor32: "La ruleta elige 5 voluntarios “forzosos amables”.",
    steps: [
      { title: "Prep", detail: "30 s para pensar un microtalento (silbido, dato, baile, chiste…)." },
      { title: "Escenario", detail: "Pasan al frente 15 s cada uno." },
      { title: "Aplauso", detail: "Aplauso de pie entre actos." },
      { title: "Cierre", detail: "Grupo elige el más sorprendente con volumen de aplauso." },
    ],
    tip: "Deja pasar si alguien se siente muy incómodo; sortea otro.",
  },
  {
    id: "preguntas-sombrero",
    title: "Sombrero de preguntas",
    tagline: "Sorteo de curiosidad",
    minutes: 7,
    energy: "baja",
    formation: "spotlight",
    spotlightCount: 3,
    illustrated: false,
    materials: "Bolsa/caja con preguntas",
    setupFor32: "3 alumnos sorteados sacan pregunta y responden; luego eligen a otro.",
    steps: [
      { title: "Sorteo", detail: "Las 3 personas de la ruleta pasan al frente." },
      { title: "Pregunta", detail: "Leen una pregunta y responden en 20 s." },
      { title: "Pasan", detail: "Eligen a alguien del público para la siguiente." },
      { title: "Fin", detail: "Después de 6 respuestas, cierran." },
    ],
    tip: "Preguntas: “¿qué app no pueden soltar?”, “¿a quién admiran?”",
  },
  {
    id: "construccion-rapida",
    title: "Torre de 90 segundos",
    tagline: "Reto Maker en equipos",
    minutes: 8,
    energy: "alta",
    formation: "equipos",
    spotlightCount: 0,
    illustrated: true,
    materials: "Hojas, cinta o clips (o solo cuadernos apilables)",
    setupFor32: "8 equipos de 4. Misma cantidad de material por mesa.",
    steps: [
      { title: "Reto", detail: "Construir la torre más alta que se sostenga sola." },
      { title: "Timer", detail: "90 s de construcción; manos arriba al acabar." },
      { title: "Medir", detail: "Docente mide o compara a ojo." },
      { title: "Debrief", detail: "1 idea: ¿qué estrategia funcionó?" },
    ],
    tip: "Sin material: torre humana de 3 niveles (con cuidado).",
  },
  {
    id: "memory-nombres",
    title: "Memoria de nombres",
    tagline: "Reto de recuerdo",
    minutes: 7,
    energy: "media",
    formation: "circulo",
    spotlightCount: 1,
    illustrated: false,
    materials: "Ninguno",
    setupFor32: "Mejor en 2 círculos de 16. Inicia quien marque la ruleta.",
    steps: [
      { title: "Ronda 1", detail: "Dicen solo su nombre en orden." },
      { title: "Reto", detail: "Una persona intenta nombrar a 5 seguidos sin error." },
      { title: "Ayuda", detail: "Si falla, el grupo da la inicial como pista." },
      { title: "Cierre", detail: "Otro voluntario intenta del otro lado del círculo." },
    ],
    tip: "Útil al inicio de semestre o con lista nueva.",
  },
  {
    id: "paso-secreto",
    title: "El paso secreto",
    tagline: "Detectar al líder oculto",
    minutes: 6,
    energy: "media",
    formation: "circulo",
    spotlightCount: 2,
    illustrated: true,
    materials: "Ninguno",
    setupFor32: "Círculo. Ruleta elige: 1 líder secreto + 1 detective (sale un momento).",
    steps: [
      { title: "Detective fuera", detail: "La persona detective sale 10 s." },
      { title: "Líder", detail: "El líder inicia gestos; todos copian disimulando." },
      { title: "Entrada", detail: "Detective entra y tiene 3 intentos para hallar al líder." },
      { title: "Reveal", detail: "Se revela; nueva ronda con otros dos sorteados." },
    ],
    tip: "Gestos grandes pero lentos; evita señalar al líder.",
  },
  {
    id: "gratitud-flash",
    title: "Gratitud flash",
    tagline: "Cierre positivo",
    minutes: 4,
    energy: "baja",
    formation: "parejas",
    spotlightCount: 0,
    illustrated: false,
    materials: "Ninguno",
    setupFor32: "Parejas sentadas. Ideal al final de clase.",
    steps: [
      { title: "Prompt", detail: "“Algo que agradecen de esta semana / de un compañero”." },
      { title: "Compartir", detail: "45 s cada uno." },
      { title: "Opcional", detail: "2 voluntarios lo dicen al grupo." },
      { title: "Salida", detail: "Docente cierra con expectativa de la próxima sesión." },
    ],
    tip: "Baja la energía y deja buen sabor de boca.",
  },
];

export const ICEBREAKER_COLORS = [
  "#34d399",
  "#22d3ee",
  "#60a5fa",
  "#a78bfa",
  "#f472b6",
  "#fb923c",
  "#facc15",
  "#4ade80",
  "#38bdf8",
  "#c084fc",
  "#f87171",
  "#2dd4bf",
];

export function energyLabel(energy: IcebreakerEnergy) {
  if (energy === "alta") return "Alta energía";
  if (energy === "media") return "Energía media";
  return "Energía baja";
}

export function formationLabel(formation: IcebreakerFormation) {
  const map: Record<IcebreakerFormation, string> = {
    circulo: "Círculo",
    parejas: "Parejas",
    trios: "Tríos",
    equipos: "Equipos",
    filas: "Filas",
    mezcla: "Mezcla libre",
    spotlight: "Al frente",
    libre: "En su lugar",
  };
  return map[formation];
}
